pub mod go;
pub mod java;
pub mod python;
pub mod registry;
pub mod rust;
pub mod semantics;
pub mod typescript;

pub use registry::semantics_for;
pub use semantics::LanguageSemantics;

use open_kioku_core::Language;
use std::path::Path;

pub fn detect_language(path: &Path) -> Language {
    if let Some(name) = path.file_name().and_then(|name| name.to_str()) {
        if name == "Dockerfile" || name.starts_with("Dockerfile.") {
            return Language::Text;
        }
    }
    match path
        .extension()
        .and_then(|ext| ext.to_str())
        .unwrap_or_default()
    {
        "rs" => Language::Rust,
        "java" => Language::Java,
        "ts" | "tsx" => Language::TypeScript,
        "js" | "jsx" | "mjs" | "cjs" => Language::JavaScript,
        "py" => Language::Python,
        "go" => Language::Go,
        "yaml" | "yml" => Language::Yaml,
        "json" => Language::Json,
        "toml" => Language::Toml,
        "tf" | "tfvars" | "hcl" => Language::Text,
        "sql" => Language::Sql,
        "md" | "mdx" => Language::Markdown,
        "txt" => Language::Text,
        _ => Language::Unknown,
    }
}

pub fn is_supported_code(language: &Language) -> bool {
    matches!(
        language,
        Language::Rust
            | Language::Java
            | Language::TypeScript
            | Language::JavaScript
            | Language::Python
            | Language::Go
            | Language::Yaml
            | Language::Json
            | Language::Toml
            | Language::Sql
            | Language::Markdown
            | Language::Text
    )
}

pub fn likely_test_path(path: &Path) -> bool {
    let value = path.to_string_lossy().to_ascii_lowercase();
    value.contains("/test/")
        || value.contains("/tests/")
        || value.ends_with("_test.rs")
        || value.ends_with("_test.go")
        || value.ends_with("test.java")
        || value.ends_with(".spec.ts")
        || value.ends_with(".test.ts")
        || value.ends_with("_test.py")
        || value.starts_with("tests/")
}

pub fn likely_vendor_path(path: &Path) -> bool {
    let value = path.to_string_lossy();
    value.starts_with("node_modules/")
        || value.starts_with("target/")
        || value.starts_with("vendor/")
        || value.starts_with(".venv/")
        || value.starts_with("dist/")
        || value.starts_with("build/")
        || value.contains("node_modules/")
        || value.contains("/target/")
        || value.contains("/vendor/")
        || value.contains("/.venv/")
        || value.contains("/dist/")
        || value.contains("/build/")
}

pub fn likely_generated(content: &str) -> bool {
    let head = content
        .lines()
        .take(8)
        .collect::<Vec<_>>()
        .join("\n")
        .to_ascii_lowercase();
    head.contains("@generated")
        || head.contains("code generated")
        || head.contains("automatically generated")
        || head.contains("do not edit")
}

/// The origin a generated file's own header names.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedOrigin {
    /// The path as written in the header, not yet resolved against the repository.
    pub path: String,
    /// 1-based line the declaration sits on.
    pub line: u32,
}

/// The number of leading lines a generation banner is looked for in; the same window
/// [`likely_generated`] scans, so a file is never flagged generated by one and origin-less by
/// the other for a reason of window size.
const GENERATED_HEADER_LINES: usize = 8;

/// A generated file that says where it came from: `automatically generated from
/// src/models/x/modular_x.py`, `Code generated by gen-stubs from api/v1.yaml`. The origin is
/// the first path-like token after the `from` that follows the word `generated` on one line;
/// a bare `DO NOT EDIT` banner declares nothing.
pub fn generated_origin(content: &str) -> Option<GeneratedOrigin> {
    content
        .lines()
        .take(GENERATED_HEADER_LINES)
        .enumerate()
        .find_map(|(index, line)| {
            let lower = line.to_ascii_lowercase();
            let generated_at = lower.find("generated")?;
            let after_generated = &lower[generated_at..];
            let from_at = after_generated.find(" from ")?;
            let start = generated_at + from_at + " from ".len();
            let mut candidate = line[start..].split_whitespace().next()?;
            // Quoting and sentence punctuation nest (`` `x.py`; `` , `(x.py).`), so peel until stable.
            loop {
                let peeled = candidate
                    .trim_matches(['`', '"', '\'', '(', ')', '<', '>', '[', ']'])
                    .trim_end_matches(['.', ',', ';', ':']);
                if peeled == candidate {
                    break;
                }
                candidate = peeled;
            }
            let candidate = candidate.strip_prefix("./").unwrap_or(candidate);
            looks_like_repository_path(candidate).then(|| GeneratedOrigin {
                path: candidate.to_string(),
                line: u32::try_from(index + 1).unwrap_or(u32::MAX),
            })
        })
}

/// A relative path with a file extension: `models/x/modular_x.py`, `./schema.graphql`. Tool
/// names ("generated from protoc"), URLs, and sentences are not.
fn looks_like_repository_path(value: &str) -> bool {
    let name = value.rsplit('/').next().unwrap_or(value);
    !value.is_empty()
        && !value.contains("://")
        && !value.starts_with('/')
        && name.contains('.')
        && !name.starts_with('.')
        && !name.ends_with('.')
        && value
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || matches!(c, '/' | '.' | '_' | '-' | '@' | '+'))
}

#[cfg(test)]
mod tests {
    use super::*;
    use open_kioku_core::{GraphEdgeType, Language, ReceiverKind, SymbolKind};

    #[test]
    fn generated_origin_reads_the_path_the_header_names() {
        let banner = "#            🚨🚨🚨🚨🚨🚨\n#   This file was automatically generated from src/models/orbit/modular_orbit.py.\n#   Do NOT edit this file manually.\n";
        assert_eq!(
            generated_origin(banner),
            Some(GeneratedOrigin {
                path: "src/models/orbit/modular_orbit.py".into(),
                line: 2,
            })
        );
        assert_eq!(
            generated_origin(
                "// Code generated by gen-client from `api/openapi.yaml`; DO NOT EDIT.\n"
            )
            .map(|origin| origin.path),
            Some("api/openapi.yaml".into())
        );
        assert!(likely_generated(banner));
    }

    #[test]
    fn generated_origin_ignores_banners_that_name_no_file() {
        assert_eq!(
            generated_origin("// Code generated by protoc-gen-go. DO NOT EDIT.\n"),
            None
        );
        assert_eq!(
            generated_origin("// generated from the schema registry\n"),
            None
        );
        assert_eq!(
            generated_origin("// generated from https://example.invalid/schema.json\n"),
            None
        );
        assert_eq!(generated_origin("// generated from /etc/passwd\n"), None);
        // Outside the header window the declaration is not a banner.
        let late = format!(
            "{}\n// generated from a/b.py\n",
            "\n".repeat(GENERATED_HEADER_LINES)
        );
        assert_eq!(generated_origin(&late), None);
    }

    #[test]
    fn registers_all_six_tier_one_languages() {
        let langs = [
            Language::Java,
            Language::TypeScript,
            Language::JavaScript,
            Language::Python,
            Language::Go,
            Language::Rust,
        ];
        for lang in &langs {
            assert!(semantics_for(lang).is_some());
        }
    }

    #[test]
    fn classifies_receivers_correctly() {
        let java_sem = semantics_for(&Language::Java).unwrap();
        assert_eq!(java_sem.classify_receiver("this"), ReceiverKind::Self_);
        assert_eq!(java_sem.classify_receiver("this.repo"), ReceiverKind::Self_);
        assert_eq!(java_sem.classify_receiver("super"), ReceiverKind::Super);
        assert_eq!(
            java_sem.classify_receiver("super.repo"),
            ReceiverKind::Value
        );
        assert_eq!(java_sem.classify_receiver("Repo"), ReceiverKind::Type);
        assert_eq!(java_sem.classify_receiver("Super"), ReceiverKind::Type);

        let ts_sem = semantics_for(&Language::TypeScript).unwrap();
        assert_eq!(ts_sem.classify_receiver("this.repo"), ReceiverKind::Self_);
        assert_eq!(ts_sem.classify_receiver("super"), ReceiverKind::Super);
        assert_eq!(ts_sem.classify_receiver("super.repo"), ReceiverKind::Value);
        assert_eq!(ts_sem.classify_receiver("Super"), ReceiverKind::Type);

        let js_sem = semantics_for(&Language::JavaScript).unwrap();
        assert_eq!(js_sem.classify_receiver("this.repo"), ReceiverKind::Self_);
        assert_eq!(js_sem.classify_receiver("super"), ReceiverKind::Super);
        assert_eq!(js_sem.classify_receiver("super.repo"), ReceiverKind::Value);
        assert_eq!(js_sem.classify_receiver("Super"), ReceiverKind::Type);

        let py_sem = semantics_for(&Language::Python).unwrap();
        assert_eq!(py_sem.classify_receiver("self"), ReceiverKind::Self_);
        assert_eq!(py_sem.classify_receiver("self.repo"), ReceiverKind::Self_);
        assert_eq!(py_sem.classify_receiver("cls"), ReceiverKind::Self_);
        assert_eq!(py_sem.classify_receiver("cls.repo"), ReceiverKind::Self_);
        assert_eq!(py_sem.classify_receiver("super()"), ReceiverKind::Super);
        assert_eq!(
            py_sem.classify_receiver("super().repo"),
            ReceiverKind::Value
        );
    }

    #[test]
    fn enforces_relationship_compatibility() {
        let sem = semantics_for(&Language::Rust).unwrap();
        assert!(sem.compatible_relationship(
            SymbolKind::Function,
            SymbolKind::Method,
            GraphEdgeType::Calls
        ));
        assert!(!sem.compatible_relationship(
            SymbolKind::Function,
            SymbolKind::Field,
            GraphEdgeType::Calls
        ));
    }
}
