[package]
name = "open-kioku-storage"
version.workspace = true
edition.workspace = true
description = "Storage traits and index abstractions for Open Kioku."
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
chrono.workspace = true
open-kioku-core = { version = "3.0.4", path = "../open-kioku-core" }
open-kioku-errors = { version = "3.0.4", path = "../open-kioku-errors" }
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true
