#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OK_BIN="${OK_BIN:-$ROOT/target/debug/ok}"
OK_DISPLAY="${OK_DISPLAY:-target/debug/ok}"
PROOF_REPO="${PROOF_REPO:-/tmp/open-kioku-proof}"
OUT="${OUT:-$ROOT/docs/proof.md}"

if [[ ! -x "$OK_BIN" ]]; then
  cargo build -p open-kioku-cli --manifest-path "$ROOT/Cargo.toml"
fi

rm -rf "$PROOF_REPO"

demo_output="$("$OK_BIN" demo --path "$PROOF_REPO" --force)"
status_output="$("$OK_BIN" status "$PROOF_REPO" --markdown)"
setup_output="$("$OK_BIN" setup audit "$PROOF_REPO" --markdown)"
search_output="$("$OK_BIN" --repo "$PROOF_REPO" search token --limit 5)"
impact_output="$("$OK_BIN" --repo "$PROOF_REPO" impact --file src/auth.rs)"
plan_output="$("$OK_BIN" --repo "$PROOF_REPO" plan token --format markdown)"
mcp_output="$(printf '%s\n' \
  '{"jsonrpc":"2.0","id":1,"method":"tools/list"}' \
  '{"jsonrpc":"2.0","id":2,"method":"tools/call","params":{"name":"plan_change","arguments":{"task":"token","format":"markdown"}}}' \
  | "$OK_BIN" mcp serve --repo "$PROOF_REPO" --read-only)"

cat > "$OUT" <<EOF
# Open Kioku Proof

Generated by \`scripts/generate-proof.sh\`.

## Environment

- Command under test: \`$OK_DISPLAY\`
- Demo repo: \`$PROOF_REPO\`
- Task query: \`token\`

## Demo Setup

\`\`\`text
$demo_output
\`\`\`

## Status

\`\`\`sh
$OK_DISPLAY status $PROOF_REPO --markdown
\`\`\`

\`\`\`markdown
$status_output
\`\`\`

## Setup Audit

\`\`\`sh
$OK_DISPLAY setup audit $PROOF_REPO --markdown
\`\`\`

\`\`\`markdown
$setup_output
\`\`\`

## Search

\`\`\`sh
$OK_DISPLAY --repo $PROOF_REPO search token --limit 5
\`\`\`

\`\`\`json
$search_output
\`\`\`

## Impact

\`\`\`sh
$OK_DISPLAY --repo $PROOF_REPO impact --file src/auth.rs
\`\`\`

\`\`\`json
$impact_output
\`\`\`

## Plan

\`\`\`sh
$OK_DISPLAY --repo $PROOF_REPO plan token --format markdown
\`\`\`

\`\`\`markdown
$plan_output
\`\`\`

## MCP

\`\`\`sh
printf '%s\\n' \\
  '{"jsonrpc":"2.0","id":1,"method":"tools/list"}' \\
  '{"jsonrpc":"2.0","id":2,"method":"tools/call","params":{"name":"plan_change","arguments":{"task":"token","format":"markdown"}}}' \\
  | $OK_DISPLAY mcp serve --repo $PROOF_REPO --read-only
\`\`\`

\`\`\`json
$mcp_output
\`\`\`

## Verification Commands

\`\`\`sh
cargo test -p open-kioku-plan
cargo test -p open-kioku-cli --test cli_smoke
cargo test -p open-kioku-mcp
\`\`\`
EOF

echo "wrote $OUT"
