from pathlib import Path

path = Path("crates/open-kioku-architecture/src/lib.rs")
text = path.read_text()
old = '''    use open_kioku_core::{\n        Confidence, EdgeId, Evidence, File, FileId, GraphEdgeType, GraphNodeType, IndexManifest,\n        IndexMode, IndexQuality, Language, NodeId, Repository, RepositoryId,\n    };\n'''
new = '''    use open_kioku_core::{\n        Confidence, EdgeId, Evidence, File, FileId, GraphEdgeType, GraphNodeType, IndexManifest,\n        IndexMode, IndexQuality, Language, NodeId, RelationshipProof, RelationshipProofKind,\n        Repository, RepositoryId,\n    };\n'''
if text.count(old) != 1:
    raise SystemExit(f"architecture test imports seam changed: {text.count(old)}")
text = text.replace(old, new, 1)
old = '''    fn edge(id: &str, from: &GraphNode, to: &GraphNode, edge_type: GraphEdgeType) -> GraphEdge {\n        GraphEdge {\n            id: EdgeId::new(id),\n            from: from.id.clone(),\n            to: to.id.clone(),\n            edge_type,\n            evidence: Evidence {\n                id: open_kioku_core::EvidenceId::new(format!("evidence-{id}")),\n                source: "test".into(),\n                confidence: Confidence::High,\n                message: format!("{id} evidence"),\n                ..Evidence::default()\n            },\n            ..GraphEdge::default()\n        }\n    }\n'''
new = '''    fn edge(id: &str, from: &GraphNode, to: &GraphNode, edge_type: GraphEdgeType) -> GraphEdge {\n        let proofs = match &edge_type {\n            GraphEdgeType::Calls => vec![\n                RelationshipProof::new(RelationshipProofKind::ExactCallSite, "test", 1),\n                RelationshipProof::new(RelationshipProofKind::SameScopeDefinition, "test", 1),\n            ],\n            GraphEdgeType::References => vec![RelationshipProof::new(\n                RelationshipProofKind::ExactReference,\n                "test",\n                1,\n            )],\n            GraphEdgeType::Imports => vec![RelationshipProof::new(\n                RelationshipProofKind::ModuleOrPackageBinding,\n                "test",\n                1,\n            )],\n            _ => Vec::new(),\n        };\n        let mut edge = GraphEdge {\n            id: EdgeId::new(id),\n            from: from.id.clone(),\n            to: to.id.clone(),\n            edge_type,\n            evidence: Evidence {\n                id: open_kioku_core::EvidenceId::new(format!("evidence-{id}")),\n                source: "test".into(),\n                confidence: Confidence::High,\n                message: format!("{id} evidence"),\n                ..Evidence::default()\n            },\n            ..GraphEdge::default()\n        };\n        edge.set_relationship_proofs(proofs)\n            .expect("architecture test relationship proofs must serialize");\n        edge\n    }\n'''
if text.count(old) != 1:
    raise SystemExit(f"architecture edge fixture seam changed: {text.count(old)}")
path.write_text(text.replace(old, new, 1))
