const steps={
plan:{title:'ok plan · representative output',html:`<div><span class="prompt">$</span> ok --json plan "change token expiration"</div><br><div class="good">✓ 4 primary context items</div><div class="good">✓ 4 direct impact candidates</div><div class="good">✓ 5 validation candidates</div><div class="result-title">risk: <span class="warn">medium · 0.31</span></div><div><span class="json-key">primary:</span> <span class="json-string">src/auth.rs</span>, <span class="json-string">tests/auth_flow.rs</span>, <span class="json-string">src/lib.rs</span>, <span class="json-string">README.md</span></div><br><div class="warn">! exact references, runtime, history, and coverage were unavailable</div><div class="comment"># Missing evidence lowers confidence instead of inventing certainty.</div>`},
impact:{title:'impact · from the real plan',html:`<div><span class="prompt">$</span> plan.impact.direct_impacts</div><br><div class="result-title">4 direct impact candidates</div><div><span class="json-string">src/lib.rs:7-12</span> <span class="comment"># handle_login</span></div><div><span class="json-string">tests/auth_flow.rs:4-7</span> <span class="comment"># login_returns_valid_token</span></div><div><span class="json-string">src/lib.rs:3-6</span> <span class="comment"># RequestContext</span></div><div><span class="json-string">src/lib.rs:1-2</span> <span class="comment"># auth module</span></div><br><div class="warn">! evidence quality caveat: exact symbol/reference evidence unavailable</div>`},
tests:{title:'validation · from the real plan',html:`<div><span class="prompt">$</span> plan.validation</div><br><div class="result-title">5 runnable candidates · command: <span class="json-string">cargo test</span></div><div><span class="good">01</span> issue_token</div><div><span class="good">02</span> issues_token_with_user_id</div><div><span class="good">03</span> login_returns_valid_token</div><div><span class="good">04</span> tests</div><div><span class="good">05</span> validate_token</div><br><div class="comment"># Selected before the source edit from indexed repository evidence.</div>`},
verify:{title:'ok verify · real attested run',html:`<div><span class="prompt">$</span> ok --json verify --plan plan.json --changed src/lib.rs --run-commands</div><br><div class="good">✓ cargo test · passed · exit 0</div><div class="good">✓ 2 tests passed · 0 failed</div><div class="good">✓ boundary violations: 0</div><div class="good">✓ validation attestation recorded</div><br><div class="result-title">verdict: <span class="warn">WARN</span></div><div class="warn">! exact references / runtime / history / coverage unavailable</div><div class="comment"># Tests passed. Open Kioku still refused to overstate confidence.</div>`}
};
const out=document.getElementById('tour-output'),title=document.getElementById('tour-title');
function render(step){if(!out||!title)return;out.classList.remove('fade');void out.offsetWidth;out.innerHTML=steps[step].html;title.textContent=steps[step].title;out.classList.add('fade')}
const tabs=[...document.querySelectorAll('.tab')];
function selectTab(btn,{focus=false}={}){tabs.forEach(b=>{const selected=b===btn;b.classList.toggle('active',selected);b.setAttribute('aria-selected',String(selected));b.tabIndex=selected?0:-1});out.setAttribute('aria-labelledby',btn.id);render(btn.dataset.step);if(focus)btn.focus()}
tabs.forEach((btn,index)=>{btn.addEventListener('click',()=>selectTab(btn));btn.addEventListener('keydown',event=>{let next=index;if(event.key==='ArrowDown'||event.key==='ArrowRight')next=(index+1)%tabs.length;else if(event.key==='ArrowUp'||event.key==='ArrowLeft')next=(index-1+tabs.length)%tabs.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=tabs.length-1;else return;event.preventDefault();selectTab(tabs[next],{focus:true})})});

if(out&&title)render('plan');
document.querySelectorAll('[data-copy]').forEach(btn=>btn.addEventListener('click',async()=>{const original=btn.textContent;try{await navigator.clipboard.writeText(btn.dataset.copy);btn.textContent='Copied';}catch(e){btn.textContent='Select';}setTimeout(()=>btn.textContent=original,1400)}));
const navToggle=document.querySelector('.nav-toggle'),nav=document.getElementById('primary-nav');
if(navToggle&&nav){const closeNav=()=>{nav.classList.remove('open');navToggle.setAttribute('aria-expanded','false');navToggle.querySelector('.sr-only').textContent='Open navigation'};navToggle.addEventListener('click',()=>{const open=!nav.classList.contains('open');nav.classList.toggle('open',open);navToggle.setAttribute('aria-expanded',String(open));navToggle.querySelector('.sr-only').textContent=open?'Close navigation':'Open navigation'});nav.querySelectorAll('a').forEach(link=>link.addEventListener('click',closeNav));document.addEventListener('keydown',event=>{if(event.key==='Escape')closeNav()})}
if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){document.querySelectorAll('video[autoplay]').forEach(video=>{video.pause();video.removeAttribute('autoplay')})}
