use open_kioku_config::OkConfig;
use open_kioku_core::{
    Confidence, GeneratedBy, GraphEdgeType, PruneReason, PrunedDir, SkipReason, SkipSource,
};
use open_kioku_ingest::Indexer;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

/// Every discovered source file is either indexed or attributed to exactly one skip
/// reason, per language, so an ingest rule can never drop files without the manifest
/// saying so.
#[test]
fn coverage_attributes_every_source_file_to_indexed_or_a_skip_reason() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path();
    write(root, "src/Foo.java", "class Foo {}\n");
    write(root, "src/Bar.java", "class Bar {}\n");
    // Source files are exempt from the name-based secret rule and stay indexed.
    write(root, "src/SecretStore.java", "class SecretStore {}\n");
    write(root, "vendor/dep/Dep.java", "class Dep {}\n");
    // Generated source is indexed and flagged, not dropped.
    write(
        root,
        "src/gen/Model.java",
        "// @generated by a tool\nclass Model {}\n",
    );
    write(root, "tool.py", "def run():\n    pass\n");
    // Key material and environment entries are never read, whatever their language.
    write(root, ".aws/credentials.json", "{}\n");
    write(root, "README.md", "# readme\n");
    // Not a recognised language: absent from coverage, present in skip_counts.
    write(root, "notes.xyz", "opaque\n");
    // Pruned as build output: no package declares it. Never counted, but named.
    write(root, "build/tool.py", "def build():\n    pass\n");

    let mut config = OkConfig::default();
    config.scip.enabled = false;
    config.history.enabled = false;
    let snapshot = Indexer::default().index_repo(root, &config).unwrap();
    let quality = &snapshot.manifest.quality;
    let coverage = quality
        .coverage
        .as_ref()
        .expect("a full index records coverage");

    let java = &coverage.by_language["java"];
    assert_eq!(java.discovered, 5);
    assert_eq!(java.indexed, 4);
    assert_eq!(java.generated, 1);
    assert_eq!(java.skipped[&SkipReason::Vendor], 1);
    // The vendor rule is policy: reported, but not a missing file.
    assert_eq!(java.excluded_by_policy(), 1);
    assert_eq!(java.considered(), 4);
    assert_eq!(java.percent(), Some(100.0));

    let json = &coverage.by_language["json"];
    assert_eq!(json.discovered, 1);
    assert_eq!(json.indexed, 0);
    assert_eq!(json.skipped[&SkipReason::SecretPolicy], 1);

    assert_eq!(coverage.by_language["python"].discovered, 1);
    assert_eq!(coverage.by_language["python"].indexed, 1);
    assert_eq!(coverage.pruned_dirs, 1);
    // Not a Git work tree: whether `build/` holds committed source is unknown, not zero.
    assert_eq!(
        coverage.pruned,
        vec![PrunedDir {
            path: "build".into(),
            reason: PruneReason::UndeclaredBuildDir,
            tracked_source_files: None,
        }]
    );
    assert_eq!(coverage.walk_errors, 0);
    assert!(coverage
        .summary_line()
        .ends_with("1 directory pruned as build output or dependencies: build/"));
    // Document-corpus files are in the index and count as indexed.
    assert_eq!(coverage.by_language["markdown"].indexed, 1);
    assert!(!coverage.by_language.contains_key("unknown"));
    assert_eq!(quality.skip_counts[&SkipReason::UnsupportedLanguage], 1);

    for (language, entry) in &coverage.by_language {
        assert_eq!(
            entry.discovered,
            entry.indexed + entry.skipped.values().sum::<usize>(),
            "{language}: every discovered file is indexed or skipped"
        );
        let by_source = coverage
            .policy_excluded_by_language
            .get(language)
            .map_or(0, |sources| sources.values().sum::<usize>());
        assert_eq!(
            by_source,
            entry.excluded_by_policy(),
            "{language}: every policy exclusion is attributed to a source"
        );
    }
    assert_eq!(coverage.discovered, 8);
    assert_eq!(coverage.indexed, 6);
    assert_eq!(coverage.generated, 1);
    assert_eq!(coverage.skipped[&SkipReason::SecretPolicy], 1);
    assert_eq!(coverage.excluded_by_policy(), 2);
    assert!(!coverage.below_warn_threshold());
    assert!(coverage.top_skip_reasons(3).is_empty());
    assert_eq!(
        coverage.policy_skip_reasons(),
        vec![(SkipReason::Vendor, 1), (SkipReason::SecretPolicy, 1)]
    );
    assert_eq!(coverage.policy_excluded_dirs["vendor"], 1);
    // The secret-policy path is redacted, so its directory is not recorded either.
    assert!(!coverage.policy_excluded_dirs.contains_key(".aws"));
    assert_eq!(
        coverage.policy_excluded_by_source[&SkipSource::SecurityPolicy],
        1
    );
}

/// Source under a hidden directory is excluded by policy, not missing: it is reported
/// with its directory and the setting that governs it, and never lowers the ratio.
/// On this repository, git-ignored agent worktrees under `.claude/` had read as 24.9%
/// coverage of a fully indexed tree.
#[test]
fn hidden_directories_are_policy_exclusions_outside_the_coverage_ratio() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path();
    write(root, "src/lib.rs", "pub fn live() {}\n");
    write(root, "src/main.rs", "fn main() {}\n");
    for index in 0..30 {
        write(
            root,
            &format!(".claude/worktrees/agent/src/f{index}.rs"),
            "pub fn f() {}\n",
        );
    }
    write(root, ".github/workflows/ci.yml", "on: push\n");

    let mut config = OkConfig::default();
    config.scip.enabled = false;
    config.history.enabled = false;
    let snapshot = Indexer::default().index_repo(root, &config).unwrap();
    let coverage = snapshot
        .manifest
        .quality
        .coverage
        .as_ref()
        .expect("a full index records coverage");

    let rust = &coverage.by_language["rust"];
    assert_eq!(rust.discovered, 32);
    assert_eq!(rust.indexed, 2);
    assert_eq!(rust.skipped[&SkipReason::Hidden], 30);
    assert_eq!(rust.excluded_by_policy(), 30);
    assert_eq!(rust.percent(), Some(100.0));
    assert_eq!(coverage.programming_totals(), (2, 2));
    assert_eq!(coverage.programming_percent(), Some(100.0));
    assert!(!coverage.below_warn_threshold());
    assert!(coverage.languages_below_warn_threshold().is_empty());
    assert_eq!(coverage.excluded_by_policy(), 31);
    assert_eq!(
        coverage.policy_excluded_by_source[&SkipSource::HiddenPolicy],
        31
    );
    assert_eq!(coverage.policy_excluded_dirs[".claude"], 30);
    assert_eq!(coverage.policy_excluded_dirs[".github"], 1);
    assert_eq!(
        coverage.dominant_policy_source(),
        Some((SkipSource::HiddenPolicy, 31))
    );
    assert_eq!(
        coverage.summary_line(),
        "2 of 2 programming-language files indexed (100.0%); 2 of 2 recognised files indexed (100.0%) overall; 31 excluded by policy (31 hidden; 30 under .claude/, 1 under .github/; `[security] allow_hidden_files` governs the largest share)"
    );

    // The named setting is the one that changes the answer.
    config.security.allow_hidden_files = true;
    let snapshot = Indexer::default().index_repo(root, &config).unwrap();
    let coverage = snapshot.manifest.quality.coverage.as_ref().unwrap();
    assert_eq!(coverage.by_language["rust"].indexed, 32);
    assert_eq!(coverage.excluded_by_policy(), 0);
    assert!(coverage.policy_excluded_dirs.is_empty());
}

/// `.gitignore` exclusions are counted per language, and a worktree under a hidden
/// directory that `.gitignore` also lists counts as hidden: under the default
/// `[security] allow_hidden_files = false` ingest checks the hidden rule first, so the
/// doctor's git-ignore warning does not fire on agent worktrees.
#[test]
fn git_ignored_source_is_counted_per_language_and_hidden_worktrees_stay_hidden() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path();
    write(root, ".gitignore", "src/\n.claude/\n");
    write(root, "app/main.rs", "fn main() {}\n");
    write(root, "app/lib.rs", "pub fn live() {}\n");
    for index in 0..25 {
        write(root, &format!("src/f{index}.rs"), "pub fn f() {}\n");
    }
    for index in 0..30 {
        write(
            root,
            &format!(".claude/worktrees/agent/src/w{index}.rs"),
            "pub fn w() {}\n",
        );
    }

    let mut config = OkConfig::default();
    config.scip.enabled = false;
    config.history.enabled = false;
    let snapshot = Indexer::default().index_repo(root, &config).unwrap();
    let coverage = snapshot
        .manifest
        .quality
        .coverage
        .as_ref()
        .expect("a full index records coverage");

    let rust = &coverage.by_language["rust"];
    assert_eq!(rust.discovered, 57);
    assert_eq!(rust.indexed, 2);
    assert_eq!(rust.skipped[&SkipReason::Ignored], 25);
    assert_eq!(rust.skipped[&SkipReason::Hidden], 30);
    assert_eq!(rust.considered(), 2);
    let sources = &coverage.policy_excluded_by_language["rust"];
    assert_eq!(sources[&SkipSource::GitIgnore], 25);
    assert_eq!(sources[&SkipSource::HiddenPolicy], 30);
    assert_eq!(sources.len(), 2);
    assert_eq!(
        coverage.languages_mostly_excluded_by(SkipSource::GitIgnore),
        vec![("rust", 25, 2)]
    );

    // With `src/` no longer ignored only the hidden worktree is excluded, and it is
    // never attributed to `.gitignore`.
    write(root, ".gitignore", ".claude/\n");
    let snapshot = Indexer::default().index_repo(root, &config).unwrap();
    let coverage = snapshot.manifest.quality.coverage.as_ref().unwrap();
    assert_eq!(coverage.by_language["rust"].indexed, 27);
    let sources = &coverage.policy_excluded_by_language["rust"];
    assert_eq!(sources[&SkipSource::HiddenPolicy], 30);
    assert!(!sources.contains_key(&SkipSource::GitIgnore));
    assert!(coverage
        .languages_mostly_excluded_by(SkipSource::GitIgnore)
        .is_empty());
}

/// `[index] exclude` is checked before git ignore rules, so listing git-ignored paths
/// there records them as `config_exclude`: the way to mark an intended exclusion so the
/// doctor's git-ignore warning stops.
#[test]
fn index_exclude_marks_git_ignored_source_as_an_intended_exclusion() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path();
    write(root, ".gitignore", "scratch/\n");
    write(root, "app.py", "def run():\n    pass\n");
    for index in 0..25 {
        write(
            root,
            &format!("scratch/m{index}.py"),
            "def m():\n    pass\n",
        );
    }

    let mut config = OkConfig::default();
    config.scip.enabled = false;
    config.history.enabled = false;
    let snapshot = Indexer::default().index_repo(root, &config).unwrap();
    let coverage = snapshot.manifest.quality.coverage.as_ref().unwrap();
    assert_eq!(
        coverage.policy_excluded_by_language["python"][&SkipSource::GitIgnore],
        25
    );
    assert_eq!(
        coverage.languages_mostly_excluded_by(SkipSource::GitIgnore),
        vec![("python", 25, 1)]
    );

    config.index.exclude.push("scratch/**".into());
    let snapshot = Indexer::default().index_repo(root, &config).unwrap();
    let coverage = snapshot.manifest.quality.coverage.as_ref().unwrap();
    let sources = &coverage.policy_excluded_by_language["python"];
    assert_eq!(sources[&SkipSource::ConfigExclude], 25);
    assert!(!sources.contains_key(&SkipSource::GitIgnore));
    assert!(coverage
        .languages_mostly_excluded_by(SkipSource::GitIgnore)
        .is_empty());
}

/// The hidden rule applies only under the default `[security] allow_hidden_files = false`.
/// With it on, a git-ignored worktree under `.claude/` is attributed to git ignore rules
/// and does qualify for the doctor's warning.
#[test]
fn git_ignored_worktree_counts_as_git_ignored_when_hidden_files_are_allowed() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path();
    write(root, ".gitignore", ".claude/\n");
    write(root, "app/main.rs", "fn main() {}\n");
    write(root, "app/lib.rs", "pub fn live() {}\n");
    for index in 0..30 {
        write(
            root,
            &format!(".claude/worktrees/agent/src/w{index}.rs"),
            "pub fn w() {}\n",
        );
    }

    let mut config = OkConfig::default();
    config.scip.enabled = false;
    config.history.enabled = false;
    config.security.allow_hidden_files = true;
    let snapshot = Indexer::default().index_repo(root, &config).unwrap();
    let coverage = snapshot.manifest.quality.coverage.as_ref().unwrap();
    let sources = &coverage.policy_excluded_by_language["rust"];
    assert_eq!(sources[&SkipSource::GitIgnore], 30);
    assert!(!sources.contains_key(&SkipSource::HiddenPolicy));
    assert_eq!(
        coverage.languages_mostly_excluded_by(SkipSource::GitIgnore),
        vec![("rust", 30, 2)]
    );
}

/// #477: a crate's `build` and `dist` modules are source. Discovery pruned every directory
/// with those names, so neither module was indexed and coverage still read 100%.
#[test]
fn declared_build_and_dist_modules_are_indexed() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path();
    write(
        root,
        "Cargo.toml",
        "[package]\nname = \"ledger\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    );
    write(
        root,
        "src/lib.rs",
        "pub mod build;\npub mod dist;\npub fn run() { build::compile_plan(); }\n",
    );
    write(root, "src/build/mod.rs", "pub fn compile_plan() {}\n");
    write(root, "src/dist/mod.rs", "pub fn publish_release() {}\n");
    // The `ok.toml` `ok init` writes now: its excludes no longer name `build` or `dist`.
    OkConfig::write_default(root.join("ok.toml")).unwrap();

    let mut config = OkConfig::load_from_repo(root).unwrap();
    config.scip.enabled = false;
    config.history.enabled = false;
    let snapshot = Indexer::default().index_repo(root, &config).unwrap();

    let paths = snapshot
        .files
        .iter()
        .map(|file| file.path.clone())
        .collect::<Vec<_>>();
    assert!(
        paths.contains(&PathBuf::from("src/build/mod.rs")),
        "{paths:?} {:?}",
        snapshot.skipped_paths
    );
    assert!(
        paths.contains(&PathBuf::from("src/dist/mod.rs")),
        "{paths:?}"
    );
    for name in ["compile_plan", "publish_release"] {
        assert!(
            snapshot.symbols.iter().any(|symbol| symbol.name == name),
            "{name} is an indexed symbol"
        );
    }
    let coverage = snapshot.manifest.quality.coverage.as_ref().unwrap();
    assert_eq!(coverage.pruned_dirs, 0);
    assert!(coverage.pruned.is_empty());
    assert_eq!(coverage.by_language["rust"].indexed, 3);
    assert!(snapshot
        .skipped_paths
        .iter()
        .all(|skipped| skipped.reason != SkipReason::Pruned));
}

/// The other half of #477: build output and installed packages stay pruned, each one named
/// with its reason in coverage and in the skipped paths. Untracked output never counts
/// against coverage; a source file someone committed under an undeclared `build/` does.
#[test]
fn build_output_and_dependency_directories_stay_pruned_and_are_named() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path();
    git(root, &["init", "--quiet"]);
    write(
        root,
        "Cargo.toml",
        "[workspace]\nmembers = [\"crates/tool\"]\n",
    );
    write(root, "src/lib.rs", "pub fn live() {}\n");
    // Cargo's own output, beside the manifest and carrying its cache marker.
    write(
        root,
        "target/CACHEDIR.TAG",
        "Signature: 8a477f597d28d172789f06886806bc55\n",
    );
    write(root, "target/debug/gen.rs", "pub fn generated() {}\n");
    write(
        root,
        "crates/tool/Cargo.toml",
        "[package]\nname = \"tool\"\nversion = \"0.1.0\"\n",
    );
    write(root, "crates/tool/src/lib.rs", "pub fn tool() {}\n");
    write(root, "crates/tool/target/keep.rs", "pub fn kept() {}\n");
    // Beside the root `Cargo.toml`: build output on strong evidence.
    write(root, "build/steps.py", "def step():\n    pass\n");
    // Nothing declares it and no manifest sits beside it: pruned by the weak rule.
    write(root, "tools/build/plan.py", "def plan():\n    pass\n");
    write(root, "dist/app.js", "export function app() {}\n");
    write(root, "node_modules/pkg/index.js", "module.exports = {};\n");
    write(root, ".venv/pyvenv.cfg", "home = /usr/bin\n");
    write(root, ".venv/lib/site.py", "def site():\n    pass\n");
    write(root, "vendor/dep/lib.rs", "pub fn dep() {}\n");
    // A committed dependency is listed with its tracked files but is not missing source.
    git(
        root,
        &[
            "add",
            "Cargo.toml",
            "src",
            "crates/tool/Cargo.toml",
            "crates/tool/src",
            "node_modules",
            "vendor",
        ],
    );

    let mut config = OkConfig::default();
    config.scip.enabled = false;
    config.history.enabled = false;
    let snapshot = Indexer::default().index_repo(root, &config).unwrap();

    let pruned_roots = [
        ".venv",
        "build",
        "crates/tool/target",
        "dist",
        "node_modules",
        "target",
        "tools/build",
    ];
    for file in &snapshot.files {
        assert!(
            !pruned_roots
                .iter()
                .any(|pruned| file.path.starts_with(pruned)),
            "{} is under a pruned directory",
            file.path.display()
        );
    }
    let coverage = snapshot.manifest.quality.coverage.as_ref().unwrap();
    let pruned = |path: &str, reason, tracked| PrunedDir {
        path: path.into(),
        reason,
        tracked_source_files: Some(tracked),
    };
    // The one holding a committed file first, then by path.
    assert_eq!(
        coverage.pruned,
        vec![
            pruned("node_modules", PruneReason::Dependencies, 1),
            pruned(".venv", PruneReason::VirtualEnv, 0),
            pruned("build", PruneReason::BuildOutput, 0),
            pruned("crates/tool/target", PruneReason::BuildOutput, 0),
            pruned("dist", PruneReason::BuildOutput, 0),
            pruned("target", PruneReason::BuildOutput, 0),
            pruned("tools/build", PruneReason::UndeclaredBuildDir, 0),
        ]
    );
    assert!(coverage.summary_line().ends_with(
        "7 directories pruned as build output or dependencies: node_modules/ (1 tracked source file), .venv/, build/ and 4 more"
    ), "{}", coverage.summary_line());
    assert_eq!(coverage.pruned_dirs, 7);
    assert_eq!(coverage.pruned_unlisted, 0);
    assert_eq!(coverage.pruned_source_files(), 0);
    assert!(!coverage.below_warn_threshold());
    for dir in pruned_roots {
        assert!(
            snapshot.skipped_paths.iter().any(|skipped| {
                skipped.path == Path::new(dir)
                    && skipped.reason == SkipReason::Pruned
                    && skipped.safe_to_show
            }),
            "{dir} is a named skip"
        );
    }
    // Vendored source is still a vendor-policy skip, not a pruned directory.
    assert!(snapshot.skipped_paths.iter().any(|skipped| {
        skipped.path == Path::new("vendor/dep/lib.rs") && skipped.reason == SkipReason::Vendor
    }));

    // Committing a file under the undeclared `tools/build/` makes it missing source: counted
    // as discovered and skipped `pruned`, listed first, and named in the summary. The file
    // committed under the root `build/` beside `Cargo.toml` is listed on its directory only.
    git(root, &["add", "build/steps.py", "tools/build/plan.py"]);
    let snapshot = Indexer::default().index_repo(root, &config).unwrap();
    let coverage = snapshot.manifest.quality.coverage.as_ref().unwrap();
    assert_eq!(coverage.pruned_source_files(), 1);
    let python = &coverage.by_language["python"];
    assert_eq!(python.discovered, 1);
    assert_eq!(python.skipped[&SkipReason::Pruned], 1);
    assert_eq!(python.percent(), Some(0.0));
    assert_eq!(
        coverage.pruned.first(),
        Some(&pruned("tools/build", PruneReason::UndeclaredBuildDir, 1))
    );
    assert!(coverage
        .pruned
        .contains(&pruned("build", PruneReason::BuildOutput, 1)));
    assert!(snapshot.skipped_paths.iter().any(|skipped| {
        skipped.path == Path::new("tools/build/plan.py") && skipped.reason == SkipReason::Pruned
    }));
    assert!(!snapshot
        .skipped_paths
        .iter()
        .any(|skipped| skipped.path == Path::new("build/steps.py")));
    assert!(coverage.summary_line().contains(
        "1 git-tracked source file not indexed under undeclared build directory: tools/build/"
    ));
    for (language, entry) in &coverage.by_language {
        assert_eq!(
            entry.discovered,
            entry.indexed + entry.skipped.values().sum::<usize>(),
            "{language}: every discovered file is indexed or skipped"
        );
    }
}

/// A committed `dist/` bundle beside its `package.json` (a JavaScript action, a published
/// library) is build output on strong evidence: listed with its tracked files, never counted as
/// missing source. Counting it read 20 indexed source files as 25% coverage, warned in `ok
/// doctor`, and capped every plan's confidence through a coverage gap.
#[test]
fn a_committed_bundle_beside_its_manifest_is_listed_but_not_missing_source() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path();
    git(root, &["init", "--quiet"]);
    write(root, "package.json", "{\"name\":\"ledger\"}\n");
    for index in 0..20 {
        write(
            root,
            &format!("src/m{index}.js"),
            &format!("export function entry{index}() {{}}\n"),
        );
    }
    for index in 0..60 {
        write(
            root,
            &format!("dist/m{index}.js"),
            &format!("export function bundled{index}() {{}}\n"),
        );
    }
    git(root, &["add", "."]);

    let mut config = OkConfig::default();
    config.scip.enabled = false;
    config.history.enabled = false;
    let snapshot = Indexer::default().index_repo(root, &config).unwrap();
    let coverage = snapshot.manifest.quality.coverage.as_ref().unwrap();

    assert_eq!(
        coverage.pruned,
        vec![PrunedDir {
            path: "dist".into(),
            reason: PruneReason::BuildOutput,
            tracked_source_files: Some(60),
        }]
    );
    assert_eq!(coverage.pruned_source_files(), 0);
    assert_eq!(coverage.by_language["java_script"].discovered, 20);
    assert_eq!(coverage.programming_percent(), Some(100.0));
    assert!(!coverage.below_warn_threshold());
    assert!(coverage.gaps().is_empty(), "{:?}", coverage.gaps());
    // `ok status` and `ok doctor` print the count the scan knows (#661).
    assert!(
        coverage.summary_line().ends_with(
            "1 directory pruned as build output or dependencies: dist/ (60 tracked source files)"
        ),
        "{}",
        coverage.summary_line()
    );
    // The directory is a named skip; no file under it is.
    assert!(snapshot
        .skipped_paths
        .iter()
        .all(|skipped| skipped.path == Path::new("dist") || !skipped.path.starts_with("dist")));
}

/// A pruned directory whose path is secret-like is counted, never named.
#[test]
fn a_secret_like_pruned_directory_is_counted_without_its_path() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path();
    write(root, "src/lib.rs", "pub fn live() {}\n");
    write(root, ".ssh/build/keys.py", "def keys():\n    pass\n");
    write(root, "dist/app.js", "export function app() {}\n");

    let mut config = OkConfig::default();
    config.scip.enabled = false;
    config.history.enabled = false;
    let snapshot = Indexer::default().index_repo(root, &config).unwrap();
    let coverage = snapshot.manifest.quality.coverage.as_ref().unwrap();
    assert_eq!(coverage.pruned_dirs, 2);
    assert_eq!(coverage.pruned_unlisted, 1);
    assert_eq!(
        coverage
            .pruned
            .iter()
            .map(|dir| dir.path.as_str())
            .collect::<Vec<_>>(),
        vec!["dist"]
    );
    let pruned = snapshot
        .skipped_paths
        .iter()
        .filter(|skipped| skipped.reason == SkipReason::Pruned)
        .collect::<Vec<_>>();
    assert_eq!(pruned.len(), 2);
    assert!(pruned
        .iter()
        .any(|skipped| { skipped.path == Path::new("[redacted]") && !skipped.safe_to_show }));
    assert!(!format!("{:?}", snapshot.skipped_paths).contains(".ssh"));
}

/// A workspace member whose directory is named `target` is a crate: discovery walks it (no
/// manifest or cache tag accounts for it as output), and the project model now reads its
/// manifest too, so its `crate::` paths resolve. Manifest discovery skipped every `target` by
/// name, leaving the member's files outside every package's module tree.
#[test]
fn a_crate_directory_named_target_resolves_its_crate_paths() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path();
    write(
        root,
        "Cargo.toml",
        "[workspace]\nmembers = [\"crates/target\"]\n",
    );
    write(
        root,
        "crates/target/Cargo.toml",
        "[package]\nname = \"ledger\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    );
    write(
        root,
        "crates/target/src/lib.rs",
        "pub mod post;\n\npub fn settle() {\n    crate::post::record_entry();\n}\n",
    );
    write(
        root,
        "crates/target/src/post.rs",
        "pub fn record_entry() {}\n",
    );

    let mut config = OkConfig::default();
    config.scip.enabled = false;
    config.history.enabled = false;
    let snapshot = Indexer::default().index_repo(root, &config).unwrap();
    let id = |name: &str| {
        snapshot
            .symbols
            .iter()
            .find(|symbol| symbol.name == name)
            .unwrap_or_else(|| panic!("a symbol named {name}"))
            .id
            .clone()
    };
    let (settle, record_entry) = (id("settle"), id("record_entry"));
    assert!(
        snapshot.resolved_relationships.iter().any(|edge| {
            edge.edge_type == GraphEdgeType::Calls
                && edge.from == settle
                && edge.to == record_entry
                && edge.confidence == Confidence::Exact
        }),
        "{:?}",
        snapshot.resolved_relationships
    );
}

/// A secret-like pruned directory holding committed source is still counted without its path,
/// and its tracked count is never printed beside another directory's name.
#[test]
fn a_secret_like_pruned_directory_with_tracked_source_stays_unnamed() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path();
    git(root, &["init", "--quiet"]);
    write(root, "src/lib.rs", "pub fn live() {}\n");
    write(root, ".ssh/build/keys.py", "def keys():\n    pass\n");
    write(root, ".ssh/build/more.py", "def more():\n    pass\n");
    write(root, "dist/app.js", "export function app() {}\n");
    git(root, &["add", "."]);

    let mut config = OkConfig::default();
    config.scip.enabled = false;
    config.history.enabled = false;
    let snapshot = Indexer::default().index_repo(root, &config).unwrap();
    let coverage = snapshot.manifest.quality.coverage.as_ref().unwrap();
    assert_eq!(coverage.pruned_dirs, 2);
    assert_eq!(coverage.pruned_unlisted, 1);
    let summary = coverage.summary_line();
    assert!(
        summary.ends_with("2 directories pruned as build output or dependencies: dist/ (1 tracked source file) and 1 more"),
        "{summary}"
    );
    assert!(!summary.contains(".ssh"), "{summary}");
    assert!(!summary.contains("2 tracked"), "{summary}");
}

/// `[index] keep_dirs` walks a `build` or `dist` directory the rule would prune, on a guess or
/// beside a manifest, and nothing else: its files are indexed like any other.
#[test]
fn kept_build_and_dist_directories_are_indexed() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path();
    git(root, &["init", "--quiet"]);
    write(root, "package.json", "{\"name\":\"ledger\"}\n");
    write(root, "src/index.js", "export function entry() {}\n");
    // Release scripts beside the manifest: pruned as build output by default.
    write(root, "build/release.js", "export function release() {}\n");
    // A generator package nothing declares: pruned on the weak rule by default.
    write(root, "tools/dist/emit.py", "def emit_bundle():\n    pass\n");
    write(root, "web/dist/bundle.js", "export function bundled() {}\n");
    write(root, "web/package.json", "{\"name\":\"web\"}\n");
    git(root, &["add", "."]);

    let mut config = OkConfig::default();
    config.scip.enabled = false;
    config.history.enabled = false;
    let indexed = |config: &OkConfig| {
        let snapshot = Indexer::default().index_repo(root, config).unwrap();
        let files = snapshot
            .files
            .iter()
            .map(|file| file.path.to_string_lossy().into_owned())
            .collect::<Vec<_>>();
        let pruned = snapshot
            .manifest
            .quality
            .coverage
            .as_ref()
            .unwrap()
            .pruned
            .iter()
            .map(|dir| dir.path.clone())
            .collect::<Vec<_>>();
        let symbols = snapshot
            .symbols
            .iter()
            .map(|symbol| symbol.name.clone())
            .collect::<Vec<_>>();
        (files, pruned, symbols)
    };

    let (files, pruned, _) = indexed(&config);
    assert!(!files.iter().any(|path| path.starts_with("build/")));
    assert!(!files.iter().any(|path| path.starts_with("tools/dist/")));
    // The undeclared directory holding committed source first.
    assert_eq!(pruned, vec!["tools/dist", "build", "web/dist"]);

    config.index.keep_dirs = vec!["build".into(), "tools/dist".into()];
    let (files, pruned, symbols) = indexed(&config);
    assert!(files.contains(&"build/release.js".to_string()), "{files:?}");
    assert!(
        files.contains(&"tools/dist/emit.py".to_string()),
        "{files:?}"
    );
    assert!(symbols.contains(&"release".to_string()));
    assert!(symbols.contains(&"emit_bundle".to_string()));
    // A directory the key does not list keeps its verdict.
    assert_eq!(pruned, vec!["web/dist"]);
    assert!(!files.iter().any(|path| path.starts_with("web/dist/")));
}

/// A kept directory is walked, never trusted: key material under it is still skipped by the
/// secret-path rule with its path withheld, and `[paths] deny` still applies.
#[test]
fn a_kept_directory_does_not_bypass_the_secret_path_policy() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path();
    git(root, &["init", "--quiet"]);
    write(root, "src/lib.rs", "pub fn live() {}\n");
    write(root, "deploy/dist/app.py", "def deploy():\n    pass\n");
    write(root, "deploy/dist/server.key", "PRIVATE KEY MATERIAL\n");
    write(root, "deploy/dist/.env", "TOKEN=abc123\n");
    write(root, "deploy/dist/id_rsa_deploy", "PRIVATE KEY MATERIAL\n");
    write(root, ".ssh/build/keys.py", "def keys():\n    pass\n");
    write(root, "secrets/dist/token.py", "def token():\n    pass\n");
    git(root, &["add", "."]);

    let mut config = OkConfig::default();
    config.scip.enabled = false;
    config.history.enabled = false;
    config.index.keep_dirs = vec![
        "deploy/dist".into(),
        ".ssh/build".into(),
        "secrets/dist".into(),
    ];
    let snapshot = Indexer::default().index_repo(root, &config).unwrap();
    let files = snapshot
        .files
        .iter()
        .map(|file| file.path.to_string_lossy().into_owned())
        .collect::<Vec<_>>();
    // The kept directory was walked: its ordinary source is indexed.
    assert!(
        files.contains(&"deploy/dist/app.py".to_string()),
        "{files:?}"
    );
    for blocked in [
        "deploy/dist/server.key",
        "deploy/dist/.env",
        "deploy/dist/id_rsa_deploy",
        ".ssh/build/keys.py",
        "secrets/dist/token.py",
    ] {
        assert!(!files.contains(&blocked.to_string()), "{blocked} indexed");
    }
    let skipped = &snapshot.skipped_paths;
    let shown = format!("{skipped:?}");
    for withheld in ["server.key", "id_rsa", ".env", ".ssh"] {
        assert!(!shown.contains(withheld), "{withheld} named: {shown}");
    }
    assert!(skipped.iter().any(|skip| {
        skip.reason == SkipReason::SecretPolicy
            && skip.path == Path::new("[redacted]")
            && !skip.safe_to_show
    }));
    assert!(skipped.iter().any(|skip| {
        skip.reason == SkipReason::Denied && skip.path == Path::new("secrets/dist/token.py")
    }));
    // Nothing reached a chunk either.
    assert!(!snapshot
        .chunks
        .iter()
        .any(|chunk| chunk.text.contains("PRIVATE KEY") || chunk.text.contains("abc123")));
}

/// Source named after a key type is indexed and resolved like any other module, while the key
/// files and environment file beside it stay skipped and unnamed, even with hidden files allowed
/// so the secret-path rule alone decides (#676).
#[test]
fn source_named_after_a_key_type_is_indexed_and_keys_beside_it_are_not() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path();
    git(root, &["init", "--quiet"]);
    write(
        root,
        "app/main.py",
        "from loaders.id_rsa_loader import load_key\n\n\ndef run():\n    return load_key()\n",
    );
    write(root, "loaders/__init__.py", "");
    write(
        root,
        "loaders/id_rsa_loader.py",
        "def load_key():\n    return \"keys\"\n",
    );
    write(root, "keys/id_rsa_github", "LEDGER-KEY-MATERIAL\n");
    write(root, "keys/id_rsa.txt", "LEDGER-KEY-MATERIAL\n");
    write(root, "config/.env.production", "LEDGER_TOKEN=plain\n");
    git(root, &["add", "."]);

    let mut config = OkConfig::default();
    config.scip.enabled = false;
    config.history.enabled = false;
    config.security.allow_hidden_files = true;
    let snapshot = Indexer::default().index_repo(root, &config).unwrap();
    let files = snapshot
        .files
        .iter()
        .map(|file| file.path.to_string_lossy().into_owned())
        .collect::<Vec<_>>();
    assert!(
        files.contains(&"loaders/id_rsa_loader.py".to_string()),
        "{files:?}"
    );
    for blocked in [
        "keys/id_rsa_github",
        "keys/id_rsa.txt",
        "config/.env.production",
    ] {
        assert!(!files.contains(&blocked.to_string()), "{blocked} indexed");
    }
    let id = |name: &str| {
        snapshot
            .symbols
            .iter()
            .find(|symbol| symbol.name == name)
            .unwrap_or_else(|| panic!("a symbol named {name}"))
            .id
            .clone()
    };
    let (run, load_key) = (id("run"), id("load_key"));
    assert!(
        snapshot
            .resolved_relationships
            .iter()
            .any(|edge| edge.edge_type == GraphEdgeType::Calls
                && edge.from == run
                && edge.to == load_key),
        "{:?}",
        snapshot.resolved_relationships
    );
    let skipped = &snapshot.skipped_paths;
    let secret_skips = skipped
        .iter()
        .filter(|skip| skip.reason == SkipReason::SecretPolicy)
        .collect::<Vec<_>>();
    assert_eq!(secret_skips.len(), 3, "{skipped:?}");
    assert!(secret_skips
        .iter()
        .all(|skip| skip.path == Path::new("[redacted]") && !skip.safe_to_show));
    let shown = format!("{skipped:?}");
    for withheld in ["id_rsa_github", "id_rsa.txt", ".env"] {
        assert!(!shown.contains(withheld), "{withheld} named: {shown}");
    }
    assert!(!snapshot.chunks.iter().any(|chunk| {
        chunk.text.contains("LEDGER-KEY-MATERIAL") || chunk.text.contains("LEDGER_TOKEN")
    }));
}

/// A Python repository with `app/` indexed and up to three git-ignored trees: a `venv/` that
/// holds no `pyvenv.cfg` (so discovery walks it) but installed packages under `site-packages`,
/// an `env/` Python environment, and a `generated/` tree of first-party code.
fn python_repo(root: &Path, venv: bool, env: bool, generated: bool) {
    let mut ignored = String::new();
    for index in 0..5 {
        write(
            root,
            &format!("app/ledger{index}.py"),
            "def post_entry():\n    pass\n",
        );
    }
    if venv {
        ignored.push_str("venv/\n");
        let site = "venv/lib/python3.11/site-packages";
        write(
            root,
            &format!("{site}/ledger_client-1.0.dist-info/METADATA"),
            "Name: ledger-client\n",
        );
        for index in 0..25 {
            write(
                root,
                &format!("{site}/ledger_client/m{index}.py"),
                "def fetch():\n    pass\n",
            );
        }
    }
    if env {
        ignored.push_str("env/\n");
        write(root, "env/pyvenv.cfg", "home = /usr/bin\n");
        for index in 0..10 {
            write(
                root,
                &format!("env/lib/python3.12/site-packages/store/s{index}.py"),
                "def put():\n    pass\n",
            );
        }
    }
    if generated {
        ignored.push_str("generated/\n");
        for index in 0..25 {
            write(
                root,
                &format!("generated/ledger_pb{index}.py"),
                "from app.ledger0 import post_entry\n",
            );
        }
    }
    write(root, ".gitignore", &ignored);
}

fn python_gap(venv: bool, env: bool, generated: bool) -> open_kioku_core::CoverageGap {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path();
    python_repo(root, venv, env, generated);
    let mut config = OkConfig::default();
    config.scip.enabled = false;
    config.history.enabled = false;
    let snapshot = Indexer::default().index_repo(root, &config).unwrap();
    let mut gaps = snapshot.manifest.quality.coverage.as_ref().unwrap().gaps();
    assert_eq!(gaps.len(), 1, "{gaps:?}");
    gaps.remove(0)
}

/// #503: a git-ignored tree of installed packages and a git-ignored tree of first-party source
/// in the same language were one `python` gap, named by language alone and capped alike. The
/// gap now names each directory with its class, on evidence the package tools wrote, and only
/// the files that may be first-party source cap a selection in the language.
#[test]
fn coverage_gap_names_excluded_dependency_and_source_trees_and_prices_them_apart() {
    use open_kioku_core::{
        ConfidenceBreakdown, ConfidenceSignalInput, CoverageGap, CoverageGapDir, CoverageInput,
        DependencyEvidence, ExcludedDirClass, COVERAGE_SELECTED_LANGUAGE_SIGNAL,
    };

    let mixed = python_gap(true, true, true);
    assert_eq!((mixed.missing_files, mixed.language_files), (60, 65));
    assert_eq!(mixed.dependency_files, 35);
    assert_eq!(
        mixed.excluded_dirs,
        vec![
            CoverageGapDir {
                path: "generated".into(),
                files: 25,
                class: ExcludedDirClass::Unclassified,
                evidence: None,
            },
            CoverageGapDir {
                path: "venv/lib/python3.11/site-packages".into(),
                files: 25,
                class: ExcludedDirClass::Dependencies,
                evidence: Some(DependencyEvidence::SitePackages),
            },
            CoverageGapDir {
                path: "env/lib/python3.12/site-packages".into(),
                files: 10,
                class: ExcludedDirClass::Dependencies,
                evidence: Some(DependencyEvidence::PythonEnvironment),
            },
        ]
    );
    let caveat = mixed.caveat();
    assert!(
        caveat.contains("generated/ (25 unclassified)")
            && caveat
                .contains("venv/lib/python3.11/site-packages/ (25 dependencies: site-packages)")
            && caveat.contains(
                "env/lib/python3.12/site-packages/ (10 dependencies: python-environment)"
            ),
        "{caveat}"
    );

    let dependencies_only = python_gap(true, true, false);
    assert_eq!(
        dependencies_only.dependency_files,
        dependencies_only.missing_files
    );
    assert!(dependencies_only.is_majority());
    let source_only = python_gap(false, false, true);
    assert_eq!(source_only.dependency_files, 0);

    // A selection in `app/`, a Python file, with complete evidence otherwise.
    let price = |gap: &CoverageGap| {
        ConfidenceBreakdown::from_signals(ConfidenceSignalInput {
            primary_file_count: 2,
            evidence_count: 8,
            exact_reference_count: 2,
            validation_count: 2,
            validation_with_command_count: 2,
            allowed_file_count: 2,
            runtime_signal_count: 1,
            task_relevance: 1.0,
            primary_language_keys: vec!["python".into()],
            coverage: CoverageInput::Recorded(vec![gap.clone()]),
            ..Default::default()
        })
    };
    let capped = |breakdown: &ConfidenceBreakdown| {
        breakdown
            .components
            .iter()
            .any(|component| component.signal == COVERAGE_SELECTED_LANGUAGE_SIGNAL)
    };
    // First-party source is missing: capped below `High`, as before.
    for gap in [&mixed, &source_only] {
        let breakdown = price(gap);
        assert!(breakdown.overall_score <= 0.74, "{breakdown:?}");
        assert_eq!(breakdown.overall_enum, Confidence::Medium);
        assert!(capped(&breakdown));
    }
    // Only installed packages are missing: reported, and not capped.
    let breakdown = price(&dependencies_only);
    assert!(breakdown.overall_score > 0.74, "{breakdown:?}");
    assert!(!capped(&breakdown));
    assert!(breakdown.caveats.contains(&dependencies_only.caveat()));
    assert!(breakdown
        .components
        .iter()
        .any(|component| component.signal == "index_coverage"
            && component.evidence_ids == vec!["coverage:python:git_ignore".to_string()]));
}

fn index_gaps(root: &Path) -> Vec<open_kioku_core::CoverageGap> {
    let mut config = OkConfig::default();
    config.scip.enabled = false;
    config.history.enabled = false;
    let snapshot = Indexer::default().index_repo(root, &config).unwrap();
    snapshot.manifest.quality.coverage.as_ref().unwrap().gaps()
}

/// A selection in Python with complete evidence otherwise, priced against `gap`: whether the
/// 0.74 language cap and its signal apply.
fn caps_a_python_selection(gap: &open_kioku_core::CoverageGap) -> bool {
    use open_kioku_core::{
        ConfidenceBreakdown, ConfidenceSignalInput, CoverageInput,
        COVERAGE_SELECTED_LANGUAGE_SIGNAL,
    };
    let breakdown = ConfidenceBreakdown::from_signals(ConfidenceSignalInput {
        primary_file_count: 2,
        evidence_count: 8,
        exact_reference_count: 2,
        validation_count: 2,
        validation_with_command_count: 2,
        allowed_file_count: 2,
        runtime_signal_count: 1,
        task_relevance: 1.0,
        primary_language_keys: vec!["python".into()],
        coverage: CoverageInput::Recorded(vec![gap.clone()]),
        ..Default::default()
    });
    let signal = breakdown
        .components
        .iter()
        .any(|component| component.signal == COVERAGE_SELECTED_LANGUAGE_SIGNAL);
    assert_eq!(signal, breakdown.overall_score <= 0.74, "{breakdown:?}");
    signal
}

/// #503 review: an environment marker covers the environment's installed packages, not the
/// directory holding it. `python -m venv .` run inside a first-party service writes
/// `pyvenv.cfg` beside the service's code; its git-ignored `generated/` is first-party source
/// and must still cap a Python selection, while the environment's `site-packages` does not.
#[test]
fn a_venv_created_inside_a_service_does_not_turn_its_generated_source_into_dependencies() {
    use open_kioku_core::{DependencyEvidence, ExcludedDirClass};

    let dir = tempfile::tempdir().unwrap();
    let root = dir.path();
    write(
        root,
        ".gitignore",
        "services/api/lib/\nservices/api/bin/\nservices/api/generated/\n",
    );
    write(root, "services/api/pyvenv.cfg", "home = /usr/bin\n");
    let site = "services/api/lib/python3.12/site-packages";
    write(
        root,
        &format!("{site}/pip-24.0.dist-info/METADATA"),
        "Name: pip\n",
    );
    for index in 0..20 {
        write(
            root,
            &format!("{site}/pip/m{index}.py"),
            "def run():\n    pass\n",
        );
    }
    write(
        root,
        "services/api/bin/activate_this.py",
        "def activate():\n    pass\n",
    );
    for index in 0..5 {
        write(
            root,
            &format!("services/api/handler{index}.py"),
            "def handle():\n    pass\n",
        );
    }
    for index in 0..60 {
        write(
            root,
            &format!("services/api/generated/ledger_pb{index}.py"),
            "from services.api.handler0 import handle\n",
        );
    }

    let gaps = index_gaps(root);
    assert_eq!(gaps.len(), 1, "{gaps:?}");
    let gap = &gaps[0];
    assert_eq!((gap.missing_files, gap.language_files), (81, 86));
    // Only the environment's installed packages; `bin/` and `generated/` stay source.
    assert_eq!(gap.dependency_files, 20);
    let site_dir = gap
        .excluded_dirs
        .iter()
        .find(|dir| dir.path == site)
        .unwrap_or_else(|| panic!("{gap:?}"));
    assert_eq!(site_dir.class, ExcludedDirClass::Dependencies);
    assert_eq!(
        site_dir.evidence,
        Some(DependencyEvidence::PythonEnvironment)
    );
    let services = gap
        .excluded_dirs
        .iter()
        .find(|dir| dir.path == "services")
        .unwrap_or_else(|| panic!("{gap:?}"));
    assert_eq!(services.class, ExcludedDirClass::Unclassified);
    assert_eq!(services.files, 61);
    assert!(gap.is_source_majority());
    assert!(caps_a_python_selection(gap));
}

/// #503 review: a `conda-meta/` beside a tool's git-ignored generated code says the directory
/// is a conda environment root, not that everything under it was installed.
#[test]
fn a_conda_marker_does_not_turn_sibling_generated_source_into_dependencies() {
    use open_kioku_core::ExcludedDirClass;

    let dir = tempfile::tempdir().unwrap();
    let root = dir.path();
    write(root, ".gitignore", "tools/gen/\n");
    write(root, "tools/conda-meta/history", "==> 2026-01-01 <==\n");
    for index in 0..5 {
        write(root, &format!("app/m{index}.py"), "def run():\n    pass\n");
    }
    for index in 0..30 {
        write(
            root,
            &format!("tools/gen/emit{index}.py"),
            "from app.m0 import run\n",
        );
    }

    let gaps = index_gaps(root);
    assert_eq!(gaps.len(), 1, "{gaps:?}");
    let gap = &gaps[0];
    assert_eq!(gap.missing_files, 30);
    assert_eq!(gap.dependency_files, 0);
    assert_eq!(gap.excluded_dirs.len(), 1, "{gap:?}");
    assert_eq!(gap.excluded_dirs[0].path, "tools");
    assert_eq!(gap.excluded_dirs[0].class, ExcludedDirClass::Unclassified);
    assert!(caps_a_python_selection(gap));
}

/// A checked-out submodule is another repository: `ok index` prunes it as `submodule` and names
/// it in coverage instead of failing on `git check-ignore` ("Pathspec ... is in submodule",
/// #677). Its files, a submodule nested in it, and a submodule under `node_modules` never reach
/// the index; an uninitialised one is an empty directory with nothing to miss; and one at a
/// secret-like path is counted without its name.
#[test]
fn a_checked_out_submodule_is_pruned_and_reported_not_a_failure() {
    let dir = tempfile::tempdir().unwrap();
    let sources = dir.path().join("sources");
    let inner = sources.join("inner");
    write(&inner, "inner.rs", "pub fn inner_ledger_marker() {}\n");
    git_config(&inner, &["init", "--quiet"]);
    git_config(&inner, &["add", "."]);
    git_config(&inner, &["commit", "--quiet", "-m", "inner"]);
    git_config(
        &sources,
        &["clone", "--quiet", "--bare", "inner", "inner.git"],
    );
    let ledger = sources.join("ledger");
    write(&ledger, "lib.rs", "pub fn vendored_ledger_marker() {}\n");
    git_config(&ledger, &["init", "--quiet"]);
    git_config(&ledger, &["add", "."]);
    submodule_add(&ledger, &sources.join("inner.git"), "deps/inner");
    git_config(&ledger, &["commit", "--quiet", "-m", "ledger"]);
    git_config(
        &sources,
        &["clone", "--quiet", "--bare", "ledger", "ledger.git"],
    );
    let ledger = sources.join("ledger.git");

    let root = dir.path().join("app");
    write(&root, "src/main.rs", "fn main() {}\n");
    git_config(&root, &["init", "--quiet"]);
    git_config(&root, &["add", "."]);
    git_config(&root, &["commit", "--quiet", "-m", "app"]);
    submodule_add(&root, &ledger, "libs/ledger");
    submodule_add(&root, &ledger, "libs/pending");
    submodule_add(&root, &ledger, "node_modules/ledger");
    submodule_add(&root, &ledger, "ops/.ssh");
    git_config(&root, &["commit", "--quiet", "-m", "submodules"]);
    git_config(
        &root,
        &["submodule", "--quiet", "update", "--init", "--recursive"],
    );
    git_config(
        &root,
        &["submodule", "--quiet", "deinit", "-f", "libs/pending"],
    );
    assert!(root.join("libs/ledger/deps/inner/inner.rs").is_file());
    assert!(root.join("libs/pending").is_dir());
    assert!(!root.join("libs/pending/lib.rs").exists());

    let mut config = OkConfig::default();
    config.scip.enabled = false;
    let snapshot = Indexer::default()
        .index_repo(&root, &config)
        .expect("a checked-out submodule does not fail the index");

    let paths = snapshot
        .files
        .iter()
        .map(|file| file.path.clone())
        .collect::<Vec<_>>();
    assert!(paths.contains(&PathBuf::from("src/main.rs")), "{paths:?}");
    for file in &snapshot.files {
        for outside in ["libs/", "node_modules/", "ops/"] {
            assert!(
                !file.path.starts_with(outside),
                "{} is another repository's file",
                file.path.display()
            );
        }
    }
    assert!(!snapshot.chunks.iter().any(|chunk| {
        chunk.text.contains("vendored_ledger_marker") || chunk.text.contains("inner_ledger_marker")
    }));

    let coverage = snapshot.manifest.quality.coverage.as_ref().unwrap();
    // The nested submodule sits inside `libs/ledger`, and the one under `node_modules` inside
    // installed packages: each is cut at the outermost pruned directory.
    assert_eq!(
        coverage.pruned,
        vec![
            PrunedDir {
                path: "libs/ledger".into(),
                reason: PruneReason::Submodule,
                tracked_source_files: Some(0),
            },
            PrunedDir {
                path: "node_modules".into(),
                reason: PruneReason::Dependencies,
                tracked_source_files: Some(0),
            },
        ]
    );
    assert_eq!(coverage.pruned_dirs, 3);
    assert_eq!(coverage.pruned_unlisted, 1);
    assert_eq!(coverage.pruned_source_files(), 0);
    assert_eq!(coverage.programming_percent(), Some(100.0));
    assert!(
        coverage.summary_line().contains(
            "3 directories pruned as build output, dependencies or submodules: libs/ledger/ (submodule), node_modules/"
        ),
        "{}",
        coverage.summary_line()
    );
    assert!(snapshot.skipped_paths.iter().any(|skipped| {
        skipped.path == Path::new("libs/ledger")
            && skipped.reason == SkipReason::Pruned
            && skipped.safe_to_show
    }));
    assert!(!format!("{:?}", snapshot.skipped_paths).contains(".ssh"));
    assert!(!format!("{coverage:?}").contains(".ssh"));
    assert!(!format!("{:?}", snapshot.manifest.quality).contains(".ssh"));
}

/// A `.git` left inside a directory this repository tracks (a `git init`, a tool's scratch
/// clone) cuts it from the walk like a submodule, but Git still tracks its files here, which it
/// never does under a real submodule: they count as missing source, not as another
/// repository's (#677).
#[test]
fn tracked_source_behind_a_stray_git_counts_as_missing() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path();
    write(root, "src/main.rs", "fn main() {}\n");
    write(root, "tools/ledger/lib.rs", "pub fn ledger_total() {}\n");
    git_config(root, &["init", "--quiet"]);
    git_config(root, &["add", "."]);
    git_config(root, &["commit", "--quiet", "-m", "app"]);
    git_config(&root.join("tools/ledger"), &["init", "--quiet"]);

    let mut config = OkConfig::default();
    config.scip.enabled = false;
    config.history.enabled = false;
    let snapshot = Indexer::default().index_repo(root, &config).unwrap();
    let coverage = snapshot.manifest.quality.coverage.as_ref().unwrap();
    assert_eq!(
        coverage.pruned,
        vec![PrunedDir {
            path: "tools/ledger".into(),
            reason: PruneReason::Submodule,
            tracked_source_files: Some(1),
        }]
    );
    assert_eq!(coverage.pruned_source_files(), 1);
    assert_eq!(coverage.programming_percent(), Some(50.0));
    assert!(snapshot.skipped_paths.iter().any(|skipped| {
        skipped.path == Path::new("tools/ledger/lib.rs") && skipped.reason == SkipReason::Pruned
    }));
    assert!(
        coverage.summary_line().contains(
            "1 git-tracked source file not indexed under nested repository directory: tools/ledger/"
        ),
        "{}",
        coverage.summary_line()
    );
}

/// A .NET solution after a build: MSBuild's `bin/` and `obj/` beside each project file, and an
/// `obj/` holding a restore's assets file with no project beside it, are MSBuild output, pruned
/// and named with their tracked counts. The JSON MSBuild copies into `bin/` (`appsettings.json`,
/// `*.deps.json`) and restore writes into `obj/` was indexed as source until #684. A root
/// `bin/` of first-party scripts with no project beside it is walked and indexed.
#[test]
fn a_dotnet_solution_prunes_bin_and_obj_and_keeps_a_first_party_bin() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path();
    git(root, &["init", "--quiet"]);
    write(
        root,
        "Ledger.sln",
        "Microsoft Visual Studio Solution File\n",
    );
    write(
        root,
        "src/Ledger/Ledger.csproj",
        "<Project Sdk=\"Microsoft.NET.Sdk.Web\"></Project>\n",
    );
    write(root, "src/Ledger/Entry.cs", "namespace Ledger;\n");
    write(root, "src/Ledger/appsettings.json", "{\"Logging\":{}}\n");
    write(
        root,
        "src/Ledger/wwwroot/site.js",
        "export function site() {}\n",
    );
    let output = "src/Ledger/bin/Debug/net8.0";
    write(root, &format!("{output}/Ledger.dll"), "MZ");
    write(
        root,
        &format!("{output}/appsettings.json"),
        "{\"Logging\":{}}\n",
    );
    write(
        root,
        &format!("{output}/Ledger.deps.json"),
        "{\"targets\":{}}\n",
    );
    write(
        root,
        &format!("{output}/wwwroot/site.js"),
        "export function site() {}\n",
    );
    write(
        root,
        "src/Ledger/obj/project.assets.json",
        "{\"version\":3}\n",
    );
    write(
        root,
        "src/Ledger/obj/Debug/net8.0/Ledger.AssemblyInfo.cs",
        "// <auto-generated/>\n",
    );
    // A solution-wide intermediate directory: restore output, no project beside it.
    write(
        root,
        "artifacts/obj/project.assets.json",
        "{\"version\":3}\n",
    );
    write(root, "artifacts/obj/Store.deps.json", "{\"targets\":{}}\n");
    // First-party scripts.
    write(root, "bin/deploy.py", "def deploy():\n    pass\n");
    write(root, "bin/release.sh", "#!/bin/sh\n");
    git(
        root,
        &[
            "add",
            "Ledger.sln",
            "src/Ledger/Ledger.csproj",
            "src/Ledger/Entry.cs",
            "src/Ledger/appsettings.json",
            "src/Ledger/wwwroot",
            "bin",
        ],
    );

    let snapshot = index(root);
    let pruned_roots = ["src/Ledger/bin", "src/Ledger/obj", "artifacts/obj"];
    for file in &snapshot.files {
        assert!(
            !pruned_roots
                .iter()
                .any(|pruned| file.path.starts_with(pruned)),
            "{} is under a pruned directory",
            file.path.display()
        );
    }
    for indexed in [
        "bin/deploy.py",
        "src/Ledger/appsettings.json",
        "src/Ledger/wwwroot/site.js",
    ] {
        assert!(
            snapshot
                .files
                .iter()
                .any(|file| file.path == Path::new(indexed)),
            "{indexed} is indexed"
        );
    }
    let coverage = snapshot.manifest.quality.coverage.as_ref().unwrap();
    let pruned = |path: &str| PrunedDir {
        path: path.into(),
        reason: PruneReason::MsbuildOutput,
        tracked_source_files: Some(0),
    };
    assert_eq!(
        coverage.pruned,
        vec![
            pruned("artifacts/obj"),
            pruned("src/Ledger/bin"),
            pruned("src/Ledger/obj"),
        ]
    );
    assert_eq!(coverage.pruned_source_files(), 0);
    assert_eq!(coverage.programming_percent(), Some(100.0));
    assert!(coverage.gaps().is_empty(), "{:?}", coverage.gaps());
    for dir in pruned_roots {
        assert!(
            snapshot.skipped_paths.iter().any(|skipped| {
                skipped.path == Path::new(dir) && skipped.reason == SkipReason::Pruned
            }),
            "{dir} is a named skip"
        );
    }
}

/// #684 review: a project at the root whose `bin/` holds a committed script. Before a build the
/// project file is no evidence about `bin/`, so the script is indexed. Once the build writes
/// `bin/Debug/` beside it, `bin/` is MSBuild output, and the script is git-tracked source the
/// index does not hold: counted as missing, named in the coverage caveat, and not a forbidden
/// boundary, so an edit to it needs evidence rather than failing as `forbidden_boundary`.
#[test]
fn a_committed_script_in_a_projects_bin_is_never_hidden_as_build_output() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path();
    git(root, &["init", "--quiet"]);
    write(root, ".gitignore", "bin/Debug/\nobj/\n");
    write(
        root,
        "App.csproj",
        "<Project Sdk=\"Microsoft.NET.Sdk\"></Project>\n",
    );
    write(root, "app.py", "def main():\n    pass\n");
    write(root, "bin/release_tool.py", "def release():\n    pass\n");
    git(root, &["add", ".gitignore", "App.csproj", "app.py", "bin"]);

    // No build output yet: `bin/` is walked and the script indexed.
    let snapshot = index(root);
    assert!(snapshot
        .files
        .iter()
        .any(|file| file.path == Path::new("bin/release_tool.py")));
    let coverage = snapshot.manifest.quality.coverage.as_ref().unwrap();
    assert!(coverage.pruned.is_empty(), "{:?}", coverage.pruned);
    assert_eq!(coverage.programming_percent(), Some(100.0));

    // After a build: a git-ignored `bin/Debug/net8.0/App.dll` beside the committed script.
    write(root, "bin/Debug/net8.0/App.dll", "MZ");
    let snapshot = index(root);
    assert!(!snapshot
        .files
        .iter()
        .any(|file| file.path == Path::new("bin/release_tool.py")));
    let coverage = snapshot.manifest.quality.coverage.as_ref().unwrap();
    assert_eq!(
        coverage.pruned,
        vec![PrunedDir {
            path: "bin".into(),
            reason: PruneReason::MsbuildOutput,
            tracked_source_files: Some(1),
        }]
    );
    // Missing source, not hidden output: the ratio drops and the caveat names the directory.
    assert_eq!(coverage.pruned_source_files(), 1);
    let python = &coverage.by_language["python"];
    assert_eq!((python.discovered, python.indexed), (2, 1));
    assert_eq!(python.skipped[&SkipReason::Pruned], 1);
    assert!(coverage.programming_percent() < Some(100.0));
    assert!(
        coverage
            .summary_line()
            .contains("1 git-tracked source file not indexed under MSBuild output directory: bin/"),
        "{}",
        coverage.summary_line()
    );
    assert!(snapshot.skipped_paths.iter().any(|skipped| {
        skipped.path == Path::new("bin/release_tool.py") && skipped.reason == SkipReason::Pruned
    }));
}

/// Restored NuGet packages missing from the index are installed dependencies, in either
/// layout: `packages.config`'s `packages/<Id>.<Version>/` and a global packages folder inside
/// the repository. A JavaScript library shipped as a NuGet package puts its scripts there; a
/// gap made only of them is reported and priced apart from first-party source (#684).
#[test]
fn restored_nuget_packages_are_priced_as_dependencies_in_a_coverage_gap() {
    use open_kioku_core::{CoverageGapDir, DependencyEvidence, ExcludedDirClass};

    let dir = tempfile::tempdir().unwrap();
    let root = dir.path();
    write(root, ".gitignore", "packages/\nnuget-cache/\n");
    for index in 0..5 {
        write(
            root,
            &format!("web/app{index}.js"),
            "export function render() {}\n",
        );
    }
    let package = "packages/Acme.Charts.3.6.0";
    write(root, &format!("{package}/Acme.Charts.3.6.0.nupkg"), "PK");
    for index in 0..20 {
        write(
            root,
            &format!("{package}/Content/Scripts/charts{index}.js"),
            "export function plot() {}\n",
        );
    }
    let global = "nuget-cache/packages/acme.grid/1.0.0";
    write(
        root,
        &format!("{global}/.nupkg.metadata"),
        "{\"version\":2}\n",
    );
    for index in 0..10 {
        write(
            root,
            &format!("{global}/content/grid{index}.js"),
            "export function grid() {}\n",
        );
    }

    let gaps = index_gaps(root);
    assert_eq!(gaps.len(), 1, "{gaps:?}");
    let gap = &gaps[0];
    assert_eq!((gap.missing_files, gap.language_files), (30, 35));
    assert_eq!(gap.dependency_files, 30);
    assert_eq!(
        gap.excluded_dirs,
        vec![
            CoverageGapDir {
                path: package.into(),
                files: 20,
                class: ExcludedDirClass::Dependencies,
                evidence: Some(DependencyEvidence::NugetPackages),
            },
            CoverageGapDir {
                path: "nuget-cache/packages/acme.grid".into(),
                files: 10,
                class: ExcludedDirClass::Dependencies,
                evidence: Some(DependencyEvidence::NugetGlobalPackages),
            },
        ]
    );
    assert!(gap
        .caveat()
        .contains("packages/Acme.Charts.3.6.0/ (20 dependencies: nuget-packages)"));
}

/// #684 review: a JavaScript workspace's `packages/` holding a git-ignored first-party
/// `web-gen/` beside one git-ignored restored NuGet package. Only the package is dependencies;
/// the generated TypeScript is first-party source and still caps a TypeScript selection.
#[test]
fn one_restored_package_does_not_price_its_first_party_siblings_as_dependencies() {
    use open_kioku_core::{
        ConfidenceBreakdown, ConfidenceSignalInput, CoverageInput, DependencyEvidence,
        ExcludedDirClass, COVERAGE_SELECTED_LANGUAGE_SIGNAL,
    };

    let dir = tempfile::tempdir().unwrap();
    let root = dir.path();
    write(
        root,
        ".gitignore",
        "packages/web-gen/\npackages/Newtonsoft.Json.13.0.1/\n",
    );
    write(root, "packages/ui/package.json", "{\"name\":\"ui\"}\n");
    for index in 0..5 {
        write(
            root,
            &format!("packages/ui/src/view{index}.ts"),
            "export function view() {}\n",
        );
    }
    for index in 0..20 {
        write(
            root,
            &format!("packages/web-gen/client{index}.ts"),
            "export function call() {}\n",
        );
    }
    let package = "packages/Newtonsoft.Json.13.0.1";
    write(
        root,
        &format!("{package}/Newtonsoft.Json.13.0.1.nupkg"),
        "PK",
    );
    write(
        root,
        &format!("{package}/tools/init.ts"),
        "export function init() {}\n",
    );

    let gaps = index_gaps(root);
    let gap = gaps
        .iter()
        .find(|gap| gap.language == "type_script")
        .unwrap_or_else(|| panic!("{gaps:?}"));
    assert_eq!((gap.missing_files, gap.language_files), (21, 26));
    assert_eq!(gap.dependency_files, 1);
    let class_of = |path: &str| {
        gap.excluded_dirs
            .iter()
            .find(|dir| dir.path == path)
            .map(|dir| (dir.class, dir.evidence, dir.files))
    };
    assert_eq!(
        class_of(package),
        Some((
            ExcludedDirClass::Dependencies,
            Some(DependencyEvidence::NugetPackages),
            1
        ))
    );
    assert_eq!(
        class_of("packages"),
        Some((ExcludedDirClass::Unclassified, None, 20))
    );
    assert!(gap.is_source_majority());

    // The first-party files still cap a TypeScript selection.
    let breakdown = ConfidenceBreakdown::from_signals(ConfidenceSignalInput {
        primary_file_count: 2,
        evidence_count: 8,
        exact_reference_count: 2,
        validation_count: 2,
        validation_with_command_count: 2,
        allowed_file_count: 2,
        runtime_signal_count: 1,
        task_relevance: 1.0,
        primary_language_keys: vec!["type_script".into()],
        coverage: CoverageInput::Recorded(vec![gap.clone()]),
        ..Default::default()
    });
    assert!(breakdown.overall_score <= 0.74, "{breakdown:?}");
    assert!(breakdown
        .components
        .iter()
        .any(|component| component.signal == COVERAGE_SELECTED_LANGUAGE_SIGNAL));
}

fn index(root: &Path) -> open_kioku_ingest::IndexSnapshot {
    let mut config = OkConfig::default();
    config.scip.enabled = false;
    config.history.enabled = false;
    Indexer::default().index_repo(root, &config).unwrap()
}

/// A .NET strong-name key pair and a user-secrets store are never read; a `secrets.json`
/// elsewhere is indexed with its values redacted, as before (#684).
#[test]
fn dotnet_key_pairs_and_user_secrets_stores_are_never_indexed() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path();
    write(root, "src/Ledger/Entry.js", "export function entry() {}\n");
    write(root, "src/Ledger/Ledger.snk", "\u{7}\u{2}key");
    write(
        root,
        "ops/UserSecrets/ledger-dev/secrets.json",
        "{\"Ledger:ApiKey\":\"live-value\"}\n",
    );
    write(
        root,
        "config/secrets.json",
        "{\"Ledger:Region\":\"east\"}\n",
    );

    let mut config = OkConfig::default();
    config.scip.enabled = false;
    config.history.enabled = false;
    let snapshot = Indexer::default().index_repo(root, &config).unwrap();

    let indexed = snapshot
        .files
        .iter()
        .map(|file| file.path.to_string_lossy().into_owned())
        .collect::<Vec<_>>();
    assert!(
        indexed.contains(&"config/secrets.json".to_string()),
        "{indexed:?}"
    );
    for secret in [
        "src/Ledger/Ledger.snk",
        "ops/UserSecrets/ledger-dev/secrets.json",
    ] {
        assert!(!indexed.contains(&secret.to_string()), "{secret}");
    }
    let secret_skips = snapshot
        .skipped_paths
        .iter()
        .filter(|skipped| skipped.reason == SkipReason::SecretPolicy)
        .collect::<Vec<_>>();
    assert_eq!(secret_skips.len(), 2, "{secret_skips:?}");
    assert!(secret_skips.iter().all(|skipped| {
        skipped.source == SkipSource::SecurityPolicy
            && !skipped.safe_to_show
            && skipped.path == Path::new("[redacted]")
    }));
    let listed = format!("{:?}", snapshot.skipped_paths);
    assert!(!listed.contains("Ledger.snk") && !listed.contains("UserSecrets"));
}

/// `git` with an identity, unsigned commits, and local file transport allowed (Git refuses a
/// `file://` submodule source by default since 2.38.1).
fn git_config(root: &Path, args: &[&str]) {
    fs::create_dir_all(root).unwrap();
    let status = Command::new("git")
        .arg("-C")
        .arg(root)
        .args([
            "-c",
            "user.email=test@example.com",
            "-c",
            "user.name=Test User",
            "-c",
            "commit.gpgsign=false",
            "-c",
            "protocol.file.allow=always",
            "-c",
            "init.defaultBranch=main",
        ])
        .args(args)
        .status()
        .unwrap();
    assert!(status.success(), "git {args:?} failed");
}

fn submodule_add(root: &Path, source: &Path, path: &str) {
    let source = source.to_str().unwrap();
    git_config(root, &["submodule", "--quiet", "add", source, path]);
}

fn git(root: &Path, args: &[&str]) {
    let status = Command::new("git")
        .arg("-C")
        .arg(root)
        .args(args)
        .status()
        .unwrap();
    assert!(status.success(), "git {args:?} failed");
}

/// C# files parsed with syntax errors are indexed and named beside the ratio; a generated file
/// records which rule flagged it; the parts of a partial type share the accessibility one declares.
#[test]
fn csharp_recovery_generated_rules_and_partial_accessibility_are_recorded() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path();
    write(
        root,
        "src/Ledger.cs",
        "namespace Acme;\npublic partial class Ledger { public void Post() { } }\n",
    );
    write(
        root,
        "src/Ledger.Audit.cs",
        "namespace Acme;\npartial class Ledger { public bool Load(bool async) { return Fetch(async); } }\n",
    );
    write(
        root,
        "src/Forms/Main.Designer.cs",
        "namespace Acme.Forms;\npartial class Main { }\n",
    );
    write(
        root,
        "src/Generated/Client.cs",
        "// <auto-generated>\n// Code generated by a tool. DO NOT EDIT.\nnamespace Acme;\npublic class Client { }\n",
    );
    let mut config = OkConfig::default();
    config.scip.enabled = false;
    config.history.enabled = false;
    let snapshot = Indexer::default().index_repo(root, &config).unwrap();

    let generated_by = |path: &str| {
        snapshot
            .files
            .iter()
            .find(|file| file.path == Path::new(path))
            .unwrap_or_else(|| panic!("{path} indexed"))
            .generated_by
    };
    assert_eq!(
        generated_by("src/Forms/Main.Designer.cs"),
        Some(GeneratedBy::BuildToolName)
    );
    assert_eq!(
        generated_by("src/Generated/Client.cs"),
        Some(GeneratedBy::Banner)
    );
    assert_eq!(generated_by("src/Ledger.cs"), None);

    let coverage = snapshot.manifest.quality.coverage.as_ref().unwrap();
    let csharp = &coverage.by_language["c_sharp"];
    assert_eq!((csharp.indexed, csharp.generated), (4, 2));
    assert_eq!((csharp.parsed_with_errors, csharp.pattern_fallback), (1, 0));
    assert!(
        coverage
            .summary_line()
            .contains("1 c_sharp file parsed with syntax errors"),
        "{}",
        coverage.summary_line()
    );

    let parts = snapshot
        .symbols
        .iter()
        .filter(|symbol| symbol.qualified_name == "Acme::Ledger")
        .collect::<Vec<_>>();
    assert_eq!(parts.len(), 2);
    assert!(parts
        .iter()
        .all(|part| part.visibility == open_kioku_core::Visibility::Public));
}

fn write(root: &Path, path: &str, content: &str) {
    let path = root.join(path);
    fs::create_dir_all(path.parent().unwrap()).unwrap();
    fs::write(path, content).unwrap();
}
