use open_kioku_config::OkConfig;
use open_kioku_core::{SkipReason, SkipSource};
use open_kioku_ingest::Indexer;
use std::fs;
use std::path::Path;

/// Every discovered source file is either indexed or attributed to exactly one skip
/// reason, per language, so an ingest rule can never drop files without the manifest
/// saying so.
#[test]
fn coverage_attributes_every_source_file_to_indexed_or_a_skip_reason() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path();
    write(root, "src/Foo.java", "class Foo {}\n");
    write(root, "src/Bar.java", "class Bar {}\n");
    // Source files are exempt from the name-based secret rule and stay indexed.
    write(root, "src/SecretStore.java", "class SecretStore {}\n");
    write(root, "vendor/dep/Dep.java", "class Dep {}\n");
    // Generated source is indexed and flagged, not dropped.
    write(
        root,
        "src/gen/Model.java",
        "// @generated by a tool\nclass Model {}\n",
    );
    write(root, "tool.py", "def run():\n    pass\n");
    // A non-source file the secret rule still drops by name.
    write(root, "config/secrets.json", "{}\n");
    write(root, "README.md", "# readme\n");
    // Not a recognised language: absent from coverage, present in skip_counts.
    write(root, "notes.xyz", "opaque\n");
    // Pruned by name before discovery: never counted, but reported as a blind spot.
    write(root, "build/tool.py", "def build():\n    pass\n");

    let mut config = OkConfig::default();
    config.scip.enabled = false;
    config.history.enabled = false;
    let snapshot = Indexer::default().index_repo(root, &config).unwrap();
    let quality = &snapshot.manifest.quality;
    let coverage = quality
        .coverage
        .as_ref()
        .expect("a full index records coverage");

    let java = &coverage.by_language["java"];
    assert_eq!(java.discovered, 5);
    assert_eq!(java.indexed, 4);
    assert_eq!(java.generated, 1);
    assert_eq!(java.skipped[&SkipReason::Vendor], 1);
    // The vendor rule is policy: reported, but not a missing file.
    assert_eq!(java.excluded_by_policy(), 1);
    assert_eq!(java.considered(), 4);
    assert_eq!(java.percent(), Some(100.0));

    let json = &coverage.by_language["json"];
    assert_eq!(json.discovered, 1);
    assert_eq!(json.indexed, 0);
    assert_eq!(json.skipped[&SkipReason::SecretPolicy], 1);

    assert_eq!(coverage.by_language["python"].discovered, 1);
    assert_eq!(coverage.by_language["python"].indexed, 1);
    assert_eq!(coverage.pruned_dirs, 1);
    assert_eq!(coverage.walk_errors, 0);
    assert!(coverage
        .summary_line()
        .ends_with("1 directory pruned by name (contents not counted)"));
    // Document-corpus files are in the index and count as indexed.
    assert_eq!(coverage.by_language["markdown"].indexed, 1);
    assert!(!coverage.by_language.contains_key("unknown"));
    assert_eq!(quality.skip_counts[&SkipReason::UnsupportedLanguage], 1);

    for (language, entry) in &coverage.by_language {
        assert_eq!(
            entry.discovered,
            entry.indexed + entry.skipped.values().sum::<usize>(),
            "{language}: every discovered file is indexed or skipped"
        );
        let by_source = coverage
            .policy_excluded_by_language
            .get(language)
            .map_or(0, |sources| sources.values().sum::<usize>());
        assert_eq!(
            by_source,
            entry.excluded_by_policy(),
            "{language}: every policy exclusion is attributed to a source"
        );
    }
    assert_eq!(coverage.discovered, 8);
    assert_eq!(coverage.indexed, 6);
    assert_eq!(coverage.generated, 1);
    assert_eq!(coverage.skipped[&SkipReason::SecretPolicy], 1);
    assert_eq!(coverage.excluded_by_policy(), 2);
    assert!(!coverage.below_warn_threshold());
    assert!(coverage.top_skip_reasons(3).is_empty());
    assert_eq!(
        coverage.policy_skip_reasons(),
        vec![(SkipReason::Vendor, 1), (SkipReason::SecretPolicy, 1)]
    );
    assert_eq!(coverage.policy_excluded_dirs["vendor"], 1);
    // The secret-policy path is redacted, so its directory is not recorded either.
    assert!(!coverage.policy_excluded_dirs.contains_key("config"));
    assert_eq!(
        coverage.policy_excluded_by_source[&SkipSource::SecurityPolicy],
        1
    );
}

/// Source under a hidden directory is excluded by policy, not missing: it is reported
/// with its directory and the setting that governs it, and never lowers the ratio.
/// On this repository, git-ignored agent worktrees under `.claude/` had read as 24.9%
/// coverage of a fully indexed tree.
#[test]
fn hidden_directories_are_policy_exclusions_outside_the_coverage_ratio() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path();
    write(root, "src/lib.rs", "pub fn live() {}\n");
    write(root, "src/main.rs", "fn main() {}\n");
    for index in 0..30 {
        write(
            root,
            &format!(".claude/worktrees/agent/src/f{index}.rs"),
            "pub fn f() {}\n",
        );
    }
    write(root, ".github/workflows/ci.yml", "on: push\n");

    let mut config = OkConfig::default();
    config.scip.enabled = false;
    config.history.enabled = false;
    let snapshot = Indexer::default().index_repo(root, &config).unwrap();
    let coverage = snapshot
        .manifest
        .quality
        .coverage
        .as_ref()
        .expect("a full index records coverage");

    let rust = &coverage.by_language["rust"];
    assert_eq!(rust.discovered, 32);
    assert_eq!(rust.indexed, 2);
    assert_eq!(rust.skipped[&SkipReason::Hidden], 30);
    assert_eq!(rust.excluded_by_policy(), 30);
    assert_eq!(rust.percent(), Some(100.0));
    assert_eq!(coverage.programming_totals(), (2, 2));
    assert_eq!(coverage.programming_percent(), Some(100.0));
    assert!(!coverage.below_warn_threshold());
    assert!(coverage.languages_below_warn_threshold().is_empty());
    assert_eq!(coverage.excluded_by_policy(), 31);
    assert_eq!(
        coverage.policy_excluded_by_source[&SkipSource::HiddenPolicy],
        31
    );
    assert_eq!(coverage.policy_excluded_dirs[".claude"], 30);
    assert_eq!(coverage.policy_excluded_dirs[".github"], 1);
    assert_eq!(
        coverage.dominant_policy_source(),
        Some((SkipSource::HiddenPolicy, 31))
    );
    assert_eq!(
        coverage.summary_line(),
        "2 of 2 programming-language files indexed (100.0%); 2 of 2 recognised files indexed (100.0%) overall; 31 excluded by policy (31 hidden; 30 under .claude/, 1 under .github/; `[security] allow_hidden_files` governs the largest share)"
    );

    // The named setting is the one that changes the answer.
    config.security.allow_hidden_files = true;
    let snapshot = Indexer::default().index_repo(root, &config).unwrap();
    let coverage = snapshot.manifest.quality.coverage.as_ref().unwrap();
    assert_eq!(coverage.by_language["rust"].indexed, 32);
    assert_eq!(coverage.excluded_by_policy(), 0);
    assert!(coverage.policy_excluded_dirs.is_empty());
}

/// `.gitignore` exclusions are counted per language, and a worktree under a hidden
/// directory that `.gitignore` also lists counts as hidden: under the default
/// `[security] allow_hidden_files = false` ingest checks the hidden rule first, so the
/// doctor's git-ignore warning does not fire on agent worktrees.
#[test]
fn git_ignored_source_is_counted_per_language_and_hidden_worktrees_stay_hidden() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path();
    write(root, ".gitignore", "src/\n.claude/\n");
    write(root, "app/main.rs", "fn main() {}\n");
    write(root, "app/lib.rs", "pub fn live() {}\n");
    for index in 0..25 {
        write(root, &format!("src/f{index}.rs"), "pub fn f() {}\n");
    }
    for index in 0..30 {
        write(
            root,
            &format!(".claude/worktrees/agent/src/w{index}.rs"),
            "pub fn w() {}\n",
        );
    }

    let mut config = OkConfig::default();
    config.scip.enabled = false;
    config.history.enabled = false;
    let snapshot = Indexer::default().index_repo(root, &config).unwrap();
    let coverage = snapshot
        .manifest
        .quality
        .coverage
        .as_ref()
        .expect("a full index records coverage");

    let rust = &coverage.by_language["rust"];
    assert_eq!(rust.discovered, 57);
    assert_eq!(rust.indexed, 2);
    assert_eq!(rust.skipped[&SkipReason::Ignored], 25);
    assert_eq!(rust.skipped[&SkipReason::Hidden], 30);
    assert_eq!(rust.considered(), 2);
    let sources = &coverage.policy_excluded_by_language["rust"];
    assert_eq!(sources[&SkipSource::GitIgnore], 25);
    assert_eq!(sources[&SkipSource::HiddenPolicy], 30);
    assert_eq!(sources.len(), 2);
    assert_eq!(
        coverage.languages_mostly_excluded_by(SkipSource::GitIgnore),
        vec![("rust", 25, 2)]
    );

    // With `src/` no longer ignored only the hidden worktree is excluded, and it is
    // never attributed to `.gitignore`.
    write(root, ".gitignore", ".claude/\n");
    let snapshot = Indexer::default().index_repo(root, &config).unwrap();
    let coverage = snapshot.manifest.quality.coverage.as_ref().unwrap();
    assert_eq!(coverage.by_language["rust"].indexed, 27);
    let sources = &coverage.policy_excluded_by_language["rust"];
    assert_eq!(sources[&SkipSource::HiddenPolicy], 30);
    assert!(!sources.contains_key(&SkipSource::GitIgnore));
    assert!(coverage
        .languages_mostly_excluded_by(SkipSource::GitIgnore)
        .is_empty());
}

/// `[index] exclude` is checked before git ignore rules, so listing git-ignored paths
/// there records them as `config_exclude`: the way to mark an intended exclusion so the
/// doctor's git-ignore warning stops.
#[test]
fn index_exclude_marks_git_ignored_source_as_an_intended_exclusion() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path();
    write(root, ".gitignore", "scratch/\n");
    write(root, "app.py", "def run():\n    pass\n");
    for index in 0..25 {
        write(
            root,
            &format!("scratch/m{index}.py"),
            "def m():\n    pass\n",
        );
    }

    let mut config = OkConfig::default();
    config.scip.enabled = false;
    config.history.enabled = false;
    let snapshot = Indexer::default().index_repo(root, &config).unwrap();
    let coverage = snapshot.manifest.quality.coverage.as_ref().unwrap();
    assert_eq!(
        coverage.policy_excluded_by_language["python"][&SkipSource::GitIgnore],
        25
    );
    assert_eq!(
        coverage.languages_mostly_excluded_by(SkipSource::GitIgnore),
        vec![("python", 25, 1)]
    );

    config.index.exclude.push("scratch/**".into());
    let snapshot = Indexer::default().index_repo(root, &config).unwrap();
    let coverage = snapshot.manifest.quality.coverage.as_ref().unwrap();
    let sources = &coverage.policy_excluded_by_language["python"];
    assert_eq!(sources[&SkipSource::ConfigExclude], 25);
    assert!(!sources.contains_key(&SkipSource::GitIgnore));
    assert!(coverage
        .languages_mostly_excluded_by(SkipSource::GitIgnore)
        .is_empty());
}

/// The hidden rule applies only under the default `[security] allow_hidden_files = false`.
/// With it on, a git-ignored worktree under `.claude/` is attributed to git ignore rules
/// and does qualify for the doctor's warning.
#[test]
fn git_ignored_worktree_counts_as_git_ignored_when_hidden_files_are_allowed() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path();
    write(root, ".gitignore", ".claude/\n");
    write(root, "app/main.rs", "fn main() {}\n");
    write(root, "app/lib.rs", "pub fn live() {}\n");
    for index in 0..30 {
        write(
            root,
            &format!(".claude/worktrees/agent/src/w{index}.rs"),
            "pub fn w() {}\n",
        );
    }

    let mut config = OkConfig::default();
    config.scip.enabled = false;
    config.history.enabled = false;
    config.security.allow_hidden_files = true;
    let snapshot = Indexer::default().index_repo(root, &config).unwrap();
    let coverage = snapshot.manifest.quality.coverage.as_ref().unwrap();
    let sources = &coverage.policy_excluded_by_language["rust"];
    assert_eq!(sources[&SkipSource::GitIgnore], 30);
    assert!(!sources.contains_key(&SkipSource::HiddenPolicy));
    assert_eq!(
        coverage.languages_mostly_excluded_by(SkipSource::GitIgnore),
        vec![("rust", 30, 2)]
    );
}

fn write(root: &Path, path: &str, content: &str) {
    let path = root.join(path);
    fs::create_dir_all(path.parent().unwrap()).unwrap();
    fs::write(path, content).unwrap();
}
